// Code generated by codegen. DO NOT EDIT.

package mamv2

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/client"
	"net/http"
	"net/url"
)

// AppRemovalProtectionLogsV2Service provides AppRemovalProtectionLogsV2 API operations.
type AppRemovalProtectionLogsV2Service struct {
	client *client.Client
}

// NewAppRemovalProtectionLogsV2Service creates a new AppRemovalProtectionLogsV2Service.
func NewAppRemovalProtectionLogsV2Service(c *client.Client) *AppRemovalProtectionLogsV2Service {
	return &AppRemovalProtectionLogsV2Service{client: c}
}

// AppRemovalProtectionLogsV2AppRemovalDevicesOptions holds optional query parameters for AppRemovalDevices.
type AppRemovalProtectionLogsV2AppRemovalDevicesOptions struct {
	OrganizationGroupUUID string  //
	ThresholdUUID         *string //
	ThresholdStatus       *string //
	SearchText            *string //
	Page                  *int    //
	PageSize              *int    //
	OrderBy               *string //
	SortDirection         *string //
}

// AppRemovalDevices — Gets the list of impacted devices for a threshold uuid and status in the organization group.
// Operation ID: AppRemovalProtectionLogsV2_AppRemovalDevices
// HTTP: GET /api/mam/apps/removal-protection-logs/devices
func (s *AppRemovalProtectionLogsV2Service) AppRemovalDevices(
	ctx context.Context,
	opts *AppRemovalProtectionLogsV2AppRemovalDevicesOptions,
) (http.Header, *AppRemovalDeviceResponseV2Model, error) {
	// Build endpoint path
	endpoint := "/api/mam/apps/removal-protection-logs/devices"
	// Validate required query parameters
	if opts == nil {
		return nil, nil, fmt.Errorf("AppRemovalProtectionLogsV2_AppRemovalDevices: opts must not be nil (contains required parameters)")
	}
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		query.Set("organization_group_uuid", fmt.Sprintf("%s", opts.OrganizationGroupUUID))
		if opts.ThresholdUUID != nil {
			query.Set("threshold_uuid", fmt.Sprintf("%s", *opts.ThresholdUUID))
		}
		if opts.ThresholdStatus != nil {
			query.Set("threshold_status", fmt.Sprintf("%s", *opts.ThresholdStatus))
		}
		if opts.SearchText != nil {
			query.Set("search_text", fmt.Sprintf("%s", *opts.SearchText))
		}
		if opts.Page != nil {
			query.Set("page", fmt.Sprintf("%d", *opts.Page))
		}
		if opts.PageSize != nil {
			query.Set("page_size", fmt.Sprintf("%d", *opts.PageSize))
		}
		if opts.OrderBy != nil {
			query.Set("order_by", fmt.Sprintf("%s", *opts.OrderBy))
		}
		if opts.SortDirection != nil {
			query.Set("sort_direction", fmt.Sprintf("%s", *opts.SortDirection))
		}
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response AppRemovalDeviceResponseV2Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("AppRemovalProtectionLogsV2_AppRemovalDevices: %w", err)
	}
	return headers, &response, nil
}

// GenerateAppRemovalDevicesReport — Generates and adds report for ARP impacted devices details in queue to export.
// Operation ID: AppRemovalProtectionLogsV2_GenerateAppRemovalDevicesReport
// HTTP: POST /api/mam/apps/removal-protection-logs/devices/reports
func (s *AppRemovalProtectionLogsV2Service) GenerateAppRemovalDevicesReport(
	ctx context.Context,
	request *AppRemovalDevicesReportRequestModelV2,
) (http.Header, error) {
	// Build endpoint path
	endpoint := "/api/mam/apps/removal-protection-logs/devices/reports"
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("AppRemovalProtectionLogsV2_GenerateAppRemovalDevicesReport: %w", err)
	}
	return headers, nil
}

// GenerateAppRemovalProtectionLogsReport — Generates and adds report in queue for ARP threshold details to export.
// Operation ID: AppRemovalProtectionLogsV2_GenerateAppRemovalProtectionLogsReport
// HTTP: POST /api/mam/apps/removal-protection-logs/reports
func (s *AppRemovalProtectionLogsV2Service) GenerateAppRemovalProtectionLogsReport(
	ctx context.Context,
	request *AppRemovalLogReportRequestModelV2,
) (http.Header, error) {
	// Build endpoint path
	endpoint := "/api/mam/apps/removal-protection-logs/reports"
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("AppRemovalProtectionLogsV2_GenerateAppRemovalProtectionLogsReport: %w", err)
	}
	return headers, nil
}

// GetAppRemovalProtectionLogs — Gets the list of app removal protection logs for the organization group.
// Operation ID: AppRemovalProtectionLogsV2_GetAppRemovalProtectionLogs
// HTTP: POST /api/mam/apps/removal-protection-logs
func (s *AppRemovalProtectionLogsV2Service) GetAppRemovalProtectionLogs(
	ctx context.Context,
	request *AppRemovalLogRequestModelV2,
) (http.Header, *AppRemovalProtectionLogResponseV2Model, error) {
	// Build endpoint path
	endpoint := "/api/mam/apps/removal-protection-logs"
	var response AppRemovalProtectionLogResponseV2Model
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("AppRemovalProtectionLogsV2_GetAppRemovalProtectionLogs: %w", err)
	}
	return headers, &response, nil
}

// UpdateAppRemovalThreshold — Unlock/clear the threshold and let the commands reach devices.
// Operation ID: AppRemovalProtectionLogsV2_UpdateAppRemovalThreshold
// HTTP: PUT /api/mam/apps/removal-protection-logs
func (s *AppRemovalProtectionLogsV2Service) UpdateAppRemovalThreshold(
	ctx context.Context,
	request *AppRemovalThresholdDetailV2Model,
) (http.Header, error) {
	// Build endpoint path
	endpoint := "/api/mam/apps/removal-protection-logs"
	headers, err := s.client.DoRequest(ctx, "PUT", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("AppRemovalProtectionLogsV2_UpdateAppRemovalThreshold: %w", err)
	}
	return headers, nil
}
