// Code generated by terraform-sdk-uem codegen. DO NOT EDIT.

package sdk

import (
	"context"

	"github.com/euc-uem/terraform-sdk-uem/client"
	mamv1 "github.com/euc-uem/terraform-sdk-uem/generated/mam/v1"
	mamv2 "github.com/euc-uem/terraform-sdk-uem/generated/mam/v2"
	mdmv1 "github.com/euc-uem/terraform-sdk-uem/generated/mdm/v1"
	mdmv2 "github.com/euc-uem/terraform-sdk-uem/generated/mdm/v2"
	mdmv4 "github.com/euc-uem/terraform-sdk-uem/generated/mdm/v4"
	"github.com/euc-uem/terraform-sdk-uem/generated/services"
)

// Client re-exports
type Client = client.Client
type Config = client.Config
type AuthProvider = client.AuthProvider
type BasicAuth = client.BasicAuth
type OAuth2Auth = client.OAuth2Auth
type APIError = client.APIError

var NewClient = client.NewClient
var NewBasicAuth = client.NewBasicAuth
var NewOAuth2Auth = client.NewOAuth2Auth
var ParseLocationID = client.ParseLocationID

// --- mam/v1 (from swagger_patched/mamv1.json) ---

// BlobsV1Service service
type BlobsV1Service = mamv1.BlobsV1Service

var NewBlobsV1Service = mamv1.NewBlobsV1Service

// InternalAppsV1Service service
type InternalAppsV1Service = mamv1.InternalAppsV1Service

var NewInternalAppsV1Service = mamv1.NewInternalAppsV1Service

// MacOsAppsV1Service service
type MacOsAppsV1Service = mamv1.MacOsAppsV1Service

var NewMacOsAppsV1Service = mamv1.NewMacOsAppsV1Service

type AppCriteriaApiModelV1 = mamv1.AppCriteriaApiModelV1

type AppDependencyModelV1 = mamv1.AppDependencyModelV1

type AppDeploymentOptionsModelV1 = mamv1.AppDeploymentOptionsModelV1

type AppFilesOptionsModelV1 = mamv1.AppFilesOptionsModelV1

type AppPatchModelV1 = mamv1.AppPatchModelV1

type AppTransformModelV1 = mamv1.AppTransformModelV1

type AppUnInstallProcessModelV1 = mamv1.AppUnInstallProcessModelV1

type ApplicationAssignmentModelV1 = mamv1.ApplicationAssignmentModelV1

type ApplicationAssignmentsModelV1 = mamv1.ApplicationAssignmentsModelV1

type ApplicationCategoriesModelV1 = mamv1.ApplicationCategoriesModelV1

type ApplicationConfigurationModelV1 = mamv1.ApplicationConfigurationModelV1

type ApplicationDeploymentParametersModelV1 = mamv1.ApplicationDeploymentParametersModelV1

type ApplicationSupportedModelsModelV1 = mamv1.ApplicationSupportedModelsModelV1

type CustomScriptApiModelV1 = mamv1.CustomScriptApiModelV1

type DeploymentByCriteriaApiModelV1 = mamv1.DeploymentByCriteriaApiModelV1

type DeploymentByCustomScriptApiModelV1 = mamv1.DeploymentByCustomScriptApiModelV1

type EntityV1Model = mamv1.EntityV1Model

type FileCriteriaApiModelV1 = mamv1.FileCriteriaApiModelV1

type HowToInstallApiModelV1 = mamv1.HowToInstallApiModelV1

type InternalAppModelV1 = mamv1.InternalAppModelV1

type MacOsCreateApplicationRequestV1Model = mamv1.MacOsCreateApplicationRequestV1Model

type MacOsSoftwareDeploymentSummaryModelV1 = mamv1.MacOsSoftwareDeploymentSummaryModelV1

type MsiDeploymentParameterModelV1 = mamv1.MsiDeploymentParameterModelV1

type RegistryCriteriaApiModelV1 = mamv1.RegistryCriteriaApiModelV1

type WhenToCallInstallCompleteApiModelV1 = mamv1.WhenToCallInstallCompleteApiModelV1

type WhenToInstallApiModelV1 = mamv1.WhenToInstallApiModelV1

type BlobsV1UploadBlobAsyncOptions = mamv1.BlobsV1UploadBlobAsyncOptions

// --- mam/v2 (from swagger_patched/mamv2.json) ---

// AppBookmarksV2Service service
type AppBookmarksV2Service = mamv2.AppBookmarksV2Service

var NewAppBookmarksV2Service = mamv2.NewAppBookmarksV2Service

// AppRemovalProtectionLogsV2Service service
type AppRemovalProtectionLogsV2Service = mamv2.AppRemovalProtectionLogsV2Service

var NewAppRemovalProtectionLogsV2Service = mamv2.NewAppRemovalProtectionLogsV2Service

// AppsV2Service service
type AppsV2Service = mamv2.AppsV2Service

var NewAppsV2Service = mamv2.NewAppsV2Service

// BlobsV2Service service
type BlobsV2Service = mamv2.BlobsV2Service

var NewBlobsV2Service = mamv2.NewBlobsV2Service

// EnterpriseAppRepositoryV2Service service
type EnterpriseAppRepositoryV2Service = mamv2.EnterpriseAppRepositoryV2Service

var NewEnterpriseAppRepositoryV2Service = mamv2.NewEnterpriseAppRepositoryV2Service

// InternalAppsV2Service service
type InternalAppsV2Service = mamv2.InternalAppsV2Service

var NewInternalAppsV2Service = mamv2.NewInternalAppsV2Service

// PurchasedAppsV2Service service
type PurchasedAppsV2Service = mamv2.PurchasedAppsV2Service

var NewPurchasedAppsV2Service = mamv2.NewPurchasedAppsV2Service

type AppAssignmentBspV1ModelV2 = mamv2.AppAssignmentBspV1ModelV2

type AppAssignmentDistributionV2Model = mamv2.AppAssignmentDistributionV2Model

type AppAssignmentRestrictionV1ModelV2 = mamv2.AppAssignmentRestrictionV1ModelV2

type AppAssignmentRuleDeviceV1ModelV2 = mamv2.AppAssignmentRuleDeviceV1ModelV2

type AppAssignmentRuleDevicesV1ModelListV2 = mamv2.AppAssignmentRuleDevicesV1ModelListV2

type AppAssignmentRuleV2Model = mamv2.AppAssignmentRuleV2Model

type AppAssignmentTunnelV1ModelV2 = mamv2.AppAssignmentTunnelV1ModelV2

type AppAssignmentV2Model = mamv2.AppAssignmentV2Model

type AppAssignmentVppV1ModelV2 = mamv2.AppAssignmentVppV1ModelV2

type AppConfigTemplateV2Model = mamv2.AppConfigTemplateV2Model

type AppConfigurationV1ModelV2 = mamv2.AppConfigurationV1ModelV2

type AppCriteriaApiModelV2 = mamv2.AppCriteriaApiModelV2

type AppDependencyModelV2 = mamv2.AppDependencyModelV2

type AppDeploymentOptionsModelV2 = mamv2.AppDeploymentOptionsModelV2

type AppFilesOptionsModelV2 = mamv2.AppFilesOptionsModelV2

type AppListUsingProvisioningProfileModelV2 = mamv2.AppListUsingProvisioningProfileModelV2

type AppPatchModelV2 = mamv2.AppPatchModelV2

type AppRemovalDeviceResponseV2Model = mamv2.AppRemovalDeviceResponseV2Model

type AppRemovalDeviceV2Model = mamv2.AppRemovalDeviceV2Model

type AppRemovalDevicesReportRequestModelV2 = mamv2.AppRemovalDevicesReportRequestModelV2

type AppRemovalLogReportRequestModelV2 = mamv2.AppRemovalLogReportRequestModelV2

type AppRemovalLogRequestModelV2 = mamv2.AppRemovalLogRequestModelV2

type AppRemovalProtectionLogResponseV2Model = mamv2.AppRemovalProtectionLogResponseV2Model

type AppRemovalProtectionLogV2Model = mamv2.AppRemovalProtectionLogV2Model

type AppRemovalThresholdDetailV2Model = mamv2.AppRemovalThresholdDetailV2Model

type AppTrackV2 = mamv2.AppTrackV2

type AppTransformModelV2 = mamv2.AppTransformModelV2

type AppUnInstallProcessModelV2 = mamv2.AppUnInstallProcessModelV2

type ApplicationAssignmentModelV2 = mamv2.ApplicationAssignmentModelV2

type ApplicationBranchCacheStatisticsModelV2 = mamv2.ApplicationBranchCacheStatisticsModelV2

type ApplicationCategoriesModelV2 = mamv2.ApplicationCategoriesModelV2

type ApplicationCategoriesResultV2 = mamv2.ApplicationCategoriesResultV2

type ApplicationCategoriesV2Model = mamv2.ApplicationCategoriesV2Model

type ApplicationCategoryDetailsV2 = mamv2.ApplicationCategoryDetailsV2

type ApplicationCategoryV2Model = mamv2.ApplicationCategoryV2Model

type ApplicationConfigurationModelV2 = mamv2.ApplicationConfigurationModelV2

type ApplicationConfigurationV2Model = mamv2.ApplicationConfigurationV2Model

type ApplicationDeploymentProfileMapV1ModelV2 = mamv2.ApplicationDeploymentProfileMapV1ModelV2

type ApplicationFilesOptionsV2Model = mamv2.ApplicationFilesOptionsV2Model

type ApplicationFiltersModelV2 = mamv2.ApplicationFiltersModelV2

type ApplicationPolicyV1ModelV2 = mamv2.ApplicationPolicyV1ModelV2

type ApplicationRequestV2Model = mamv2.ApplicationRequestV2Model

type ApplicationSearchV2Model = mamv2.ApplicationSearchV2Model

type ApplicationSupportedModelV2Model = mamv2.ApplicationSupportedModelV2Model

type ApplicationSupportedModelsModelV2 = mamv2.ApplicationSupportedModelsModelV2

type ApplicationSupportedModelsV2Model = mamv2.ApplicationSupportedModelsV2Model

type ApplicationTransformV2Model = mamv2.ApplicationTransformV2Model

type ApplicationUuidV2 = mamv2.ApplicationUuidV2

type ApplicationV2Model = mamv2.ApplicationV2Model

type ApplicationsProvisionProfileModelV2 = mamv2.ApplicationsProvisionProfileModelV2

type AssignmentLicenseUsageV1ModelV2 = mamv2.AssignmentLicenseUsageV1ModelV2

type BookV2Model = mamv2.BookV2Model

type BranchCacheStatisticsSummaryModelV2 = mamv2.BranchCacheStatisticsSummaryModelV2

type BulkSearchRequestV2Model = mamv2.BulkSearchRequestV2Model

type BulkSearchResponseV2Model = mamv2.BulkSearchResponseV2Model

type CustomScriptApiModelV2 = mamv2.CustomScriptApiModelV2

type DependencyInfoV2Model = mamv2.DependencyInfoV2Model

type DeploymentByCriteriaApiModelV2 = mamv2.DeploymentByCriteriaApiModelV2

type DeploymentByCustomScriptApiModelV2 = mamv2.DeploymentByCustomScriptApiModelV2

type DeviceBranchCacheStatisticsModelV2 = mamv2.DeviceBranchCacheStatisticsModelV2

type DeviceInformationV2Model = mamv2.DeviceInformationV2Model

type EnterpriseAppListResponseV2Model = mamv2.EnterpriseAppListResponseV2Model

type EnterpriseAppPackageResponseV2Model = mamv2.EnterpriseAppPackageResponseV2Model

type EnterpriseApplicationV2Model = mamv2.EnterpriseApplicationV2Model

type EntityIdV2 = mamv2.EntityIdV2

type EntityV1ModelV2 = mamv2.EntityV1ModelV2

type FileCriteriaApiModelV2 = mamv2.FileCriteriaApiModelV2

type HowToInstallApiModelV2 = mamv2.HowToInstallApiModelV2

type ImportPackageRequestV2Model = mamv2.ImportPackageRequestV2Model

type ImportPackageResponseV2Model = mamv2.ImportPackageResponseV2Model

type InstallerInfoV2Model = mamv2.InstallerInfoV2Model

type InstallerSwitchesV2Model = mamv2.InstallerSwitchesV2Model

type InternalAppModelV2 = mamv2.InternalAppModelV2

type KioskBookmarkResponseV2Model = mamv2.KioskBookmarkResponseV2Model

type LatestAppPackageInstallerInfoModelV2 = mamv2.LatestAppPackageInstallerInfoModelV2

type LatestVersionAppPackageModelV2 = mamv2.LatestVersionAppPackageModelV2

type LicensesSummaryV2Model = mamv2.LicensesSummaryV2Model

type MacOsSoftwareDeploymentSummaryModelV2 = mamv2.MacOsSoftwareDeploymentSummaryModelV2

type MsiDeploymentOptionsV1ModelV2 = mamv2.MsiDeploymentOptionsV1ModelV2

type MsiDeploymentParameterModelV2 = mamv2.MsiDeploymentParameterModelV2

type MsiDeploymentParametersV2Model = mamv2.MsiDeploymentParametersV2Model

type Office365MamIntegrationPolicyResponseModelV2 = mamv2.Office365MamIntegrationPolicyResponseModelV2

type PackageDependencyV2Model = mamv2.PackageDependencyV2Model

type PurchasedApplicationV2Model = mamv2.PurchasedApplicationV2Model

type RegistryCriteriaApiModelV2 = mamv2.RegistryCriteriaApiModelV2

type RuntimeApplicationPermissionV2 = mamv2.RuntimeApplicationPermissionV2

type SmartGroupApplicationMapV2Model = mamv2.SmartGroupApplicationMapV2Model

type VppAssignmentV2Model = mamv2.VppAssignmentV2Model

type VppDeploymentParametersV2Model = mamv2.VppDeploymentParametersV2Model

type WhenToCallInstallCompleteApiModelV2 = mamv2.WhenToCallInstallCompleteApiModelV2

type WhenToInstallApiModelV2 = mamv2.WhenToInstallApiModelV2

type AppBookmarksV2GetBookmarkListOptions = mamv2.AppBookmarksV2GetBookmarkListOptions

type AppRemovalProtectionLogsV2AppRemovalDevicesOptions = mamv2.AppRemovalProtectionLogsV2AppRemovalDevicesOptions

type AppsV2GetAppConfigTemplateAsyncOptions = mamv2.AppsV2GetAppConfigTemplateAsyncOptions

type AppsV2GetCategoriesForApplicationOptions = mamv2.AppsV2GetCategoriesForApplicationOptions

type AppsV2GetListOfDevicesOptions = mamv2.AppsV2GetListOfDevicesOptions

type AppsV2SearchOptions = mamv2.AppsV2SearchOptions

type BlobsV2UploadBlobAsyncOptions = mamv2.BlobsV2UploadBlobAsyncOptions

type EnterpriseAppRepositoryV2GetApplicationsDetailsAsyncOptions = mamv2.EnterpriseAppRepositoryV2GetApplicationsDetailsAsyncOptions

type EnterpriseAppRepositoryV2SearchApplicationsAsyncOptions = mamv2.EnterpriseAppRepositoryV2SearchApplicationsAsyncOptions

type InternalAppsV2GetApplicationBranchCacheStatisticsAsyncOptions = mamv2.InternalAppsV2GetApplicationBranchCacheStatisticsAsyncOptions

// --- mdm/v1 (from swagger_patched/mdmv1.json) ---

// DeviceSensorsV1Service service
type DeviceSensorsV1Service = mdmv1.DeviceSensorsV1Service

var NewDeviceSensorsV1Service = mdmv1.NewDeviceSensorsV1Service

// ProfilesV1Service service
type ProfilesV1Service = mdmv1.ProfilesV1Service

var NewProfilesV1Service = mdmv1.NewProfilesV1Service

// SmartGroupsService service
type SmartGroupsService = mdmv1.SmartGroupsService

var NewSmartGroupsService = mdmv1.NewSmartGroupsService

type CertificateV1 = mdmv1.CertificateV1

type DeviceSensorAssignedSmartGroupV1Model = mdmv1.DeviceSensorAssignedSmartGroupV1Model

type DeviceSensorListResponseV1Model = mdmv1.DeviceSensorListResponseV1Model

type DeviceSensorRequestV1Model = mdmv1.DeviceSensorRequestV1Model

type DeviceSensorResponseV1Model = mdmv1.DeviceSensorResponseV1Model

type DeviceSensorUpdateV1Model = mdmv1.DeviceSensorUpdateV1Model

type DeviceSensorsBulkDeleteRequestV1Model = mdmv1.DeviceSensorsBulkDeleteRequestV1Model

type EntityIdV1 = mdmv1.EntityIdV1

type SmartGroupSearchModelV1 = mdmv1.SmartGroupSearchModelV1

type SmartGroupSearchResultV1 = mdmv1.SmartGroupSearchResultV1

type DeviceSensorsV1GetDeviceSensorsOptions = mdmv1.DeviceSensorsV1GetDeviceSensorsOptions

type ProfilesV1SearchOptions = mdmv1.ProfilesV1SearchOptions

type SmartGroupsSearchOptions = mdmv1.SmartGroupsSearchOptions

// --- mdm/v2 (from swagger_patched/mdmv2.json) ---

// ProfilesV2Service service
type ProfilesV2Service = mdmv2.ProfilesV2Service

var NewProfilesV2Service = mdmv2.NewProfilesV2Service

type AllowRuleV2 = mdmv2.AllowRuleV2

type AndroidApplicationControlPayloadV2Entity = mdmv2.AndroidApplicationControlPayloadV2Entity

type AndroidApplicationV2Entity = mdmv2.AndroidApplicationV2Entity

type AndroidBookmarkSettingsPayloadV2Entity = mdmv2.AndroidBookmarkSettingsPayloadV2Entity

type AndroidConatinerVPNMocanaSettingsV2 = mdmv2.AndroidConatinerVPNMocanaSettingsV2

type AndroidConatinerVPNPayloadV2Entity = mdmv2.AndroidConatinerVPNPayloadV2Entity

type AndroidConatinerVPNPulseSecureSettingsV2 = mdmv2.AndroidConatinerVPNPulseSecureSettingsV2

type AndroidContainerAppControlPayloadV2Entity = mdmv2.AndroidContainerAppControlPayloadV2Entity

type AndroidContainerBookmarkPayloadV2Entity = mdmv2.AndroidContainerBookmarkPayloadV2Entity

type AndroidContainerBrowserPayloadV2Entity = mdmv2.AndroidContainerBrowserPayloadV2Entity

type AndroidContainerCredentialsPayloadV2Entity = mdmv2.AndroidContainerCredentialsPayloadV2Entity

type AndroidContainerEasPayloadV2Entity = mdmv2.AndroidContainerEasPayloadV2Entity

type AndroidContainerEmailPayloadV2Entity = mdmv2.AndroidContainerEmailPayloadV2Entity

type AndroidContainerPasscodePayloadV2Entity = mdmv2.AndroidContainerPasscodePayloadV2Entity

type AndroidContainerSingleSignOnPayloadV2Entity = mdmv2.AndroidContainerSingleSignOnPayloadV2Entity

type AndroidContainerSmartCardPayloadV2Entity = mdmv2.AndroidContainerSmartCardPayloadV2Entity

type AndroidContainerVpnNetMotionSettingsV2 = mdmv2.AndroidContainerVpnNetMotionSettingsV2

type AndroidCredentialsPayloadV2Entity = mdmv2.AndroidCredentialsPayloadV2Entity

type AndroidCustomSettingsPayloadV2Entity = mdmv2.AndroidCustomSettingsPayloadV2Entity

type AndroidDateTimePayloadV2Entity = mdmv2.AndroidDateTimePayloadV2Entity

type AndroidDeviceProfileV2Entity = mdmv2.AndroidDeviceProfileV2Entity

type AndroidEASPayloadV2Entity = mdmv2.AndroidEASPayloadV2Entity

type AndroidEmailPayloadV2Entity = mdmv2.AndroidEmailPayloadV2Entity

type AndroidForWorkAppPasscodePayloadV2Entity = mdmv2.AndroidForWorkAppPasscodePayloadV2Entity

type AndroidForWorkAppPermissionsV2Entity = mdmv2.AndroidForWorkAppPermissionsV2Entity

type AndroidForWorkAppRuntimePermissionV2Entity = mdmv2.AndroidForWorkAppRuntimePermissionV2Entity

type AndroidForWorkApplicationControlPayloadV2Entity = mdmv2.AndroidForWorkApplicationControlPayloadV2Entity

type AndroidForWorkAutoUpdatePayloadV2Entity = mdmv2.AndroidForWorkAutoUpdatePayloadV2Entity

type AndroidForWorkChromeBrowserPayloadV2Entity = mdmv2.AndroidForWorkChromeBrowserPayloadV2Entity

type AndroidForWorkCopeApplicationControlPayloadV2Entity = mdmv2.AndroidForWorkCopeApplicationControlPayloadV2Entity

type AndroidForWorkCredentialsPayloadV2Entity = mdmv2.AndroidForWorkCredentialsPayloadV2Entity

type AndroidForWorkCustomMessagesPayloadV2Entity = mdmv2.AndroidForWorkCustomMessagesPayloadV2Entity

type AndroidForWorkCustomSettingsPayloadV2Entity = mdmv2.AndroidForWorkCustomSettingsPayloadV2Entity

type AndroidForWorkDevicePasscodePayloadV2Entity = mdmv2.AndroidForWorkDevicePasscodePayloadV2Entity

type AndroidForWorkEASAirWatchInboxSettingsV2 = mdmv2.AndroidForWorkEASAirWatchInboxSettingsV2

type AndroidForWorkEASPayloadV2Entity = mdmv2.AndroidForWorkEASPayloadV2Entity

type AndroidForWorkEASWorkManageSettingsV2 = mdmv2.AndroidForWorkEASWorkManageSettingsV2

type AndroidForWorkFactoryResetProtectionPayloadV2Entity = mdmv2.AndroidForWorkFactoryResetProtectionPayloadV2Entity

type AndroidForWorkKioskPayloadV2Entity = mdmv2.AndroidForWorkKioskPayloadV2Entity

type AndroidForWorkOemDateTimePayloadV2Entity = mdmv2.AndroidForWorkOemDateTimePayloadV2Entity

type AndroidForWorkOemDisplayPayloadV2Entity = mdmv2.AndroidForWorkOemDisplayPayloadV2Entity

type AndroidForWorkOemRestrictionsPayloadV2Entity = mdmv2.AndroidForWorkOemRestrictionsPayloadV2Entity

type AndroidForWorkOemSoundPayloadV2Entity = mdmv2.AndroidForWorkOemSoundPayloadV2Entity

type AndroidForWorkOemWifiPayloadV2Enity = mdmv2.AndroidForWorkOemWifiPayloadV2Enity

type AndroidForWorkPasscodePayloadV2Entity = mdmv2.AndroidForWorkPasscodePayloadV2Entity

type AndroidForWorkPermissionsPayloadV2Entity = mdmv2.AndroidForWorkPermissionsPayloadV2Entity

type AndroidForWorkProxyPayloadV2Entity = mdmv2.AndroidForWorkProxyPayloadV2Entity

type AndroidForWorkRestrictionsPayloadV2Entity = mdmv2.AndroidForWorkRestrictionsPayloadV2Entity

type AndroidForWorkSamsungAPNPayloadV2Entity = mdmv2.AndroidForWorkSamsungAPNPayloadV2Entity

type AndroidForWorkSamsungDateTimePayloadV2Entity = mdmv2.AndroidForWorkSamsungDateTimePayloadV2Entity

type AndroidForWorkSamsungFirewallPayloadV2Entity = mdmv2.AndroidForWorkSamsungFirewallPayloadV2Entity

type AndroidForWorkSamsungPasscodePayloadV2Entity = mdmv2.AndroidForWorkSamsungPasscodePayloadV2Entity

type AndroidForWorkSamsungRestrictionsPayloadV2Entity = mdmv2.AndroidForWorkSamsungRestrictionsPayloadV2Entity

type AndroidForWorkSingleAppEntityV2 = mdmv2.AndroidForWorkSingleAppEntityV2

type AndroidForWorkSingleAppModePayloadV2Entity = mdmv2.AndroidForWorkSingleAppModePayloadV2Entity

type AndroidForWorkSystemUpdatesV2Entity = mdmv2.AndroidForWorkSystemUpdatesV2Entity

type AndroidForWorkVPNPayloadV2Entity = mdmv2.AndroidForWorkVPNPayloadV2Entity

type AndroidForWorkWifiPayloadV2Entity = mdmv2.AndroidForWorkWifiPayloadV2Entity

type AndroidForWorkWorkProfileRestrictionsPayloadV2Entity = mdmv2.AndroidForWorkWorkProfileRestrictionsPayloadV2Entity

type AndroidForWorkZebraMxPayloadV2Entity = mdmv2.AndroidForWorkZebraMxPayloadV2Entity

type AndroidKioskPayloadV2Entity = mdmv2.AndroidKioskPayloadV2Entity

type AndroidMaxDataUsageEntityV2 = mdmv2.AndroidMaxDataUsageEntityV2

type AndroidPasscodePayloadV2Entity = mdmv2.AndroidPasscodePayloadV2Entity

type AndroidRestrictionsPayloadV2Entity = mdmv2.AndroidRestrictionsPayloadV2Entity

type AndroidSystemUpdateApiFreezePeriodV2 = mdmv2.AndroidSystemUpdateApiFreezePeriodV2

type AndroidVpnPayloadV2Entity = mdmv2.AndroidVpnPayloadV2Entity

type AndroidWifiPayloadV2Entity = mdmv2.AndroidWifiPayloadV2Entity

type AppNotificationV2Entity = mdmv2.AppNotificationV2Entity

type AppleAppLockPayloadV2Entity = mdmv2.AppleAppLockPayloadV2Entity

type AppleCredentialsPayloadV2Entity = mdmv2.AppleCredentialsPayloadV2Entity

type AppleCustomSettingsPayloadV2Entity = mdmv2.AppleCustomSettingsPayloadV2Entity

type AppleDeviceProfileV2Entity = mdmv2.AppleDeviceProfileV2Entity

type AppleDomainsPayloadV2Entity = mdmv2.AppleDomainsPayloadV2Entity

type AppleEASAWMailClientPayloadV2Entity = mdmv2.AppleEASAWMailClientPayloadV2Entity

type AppleEASAWMailCredentialPayloadV2Entity = mdmv2.AppleEASAWMailCredentialPayloadV2Entity

type AppleEASNativeMailClientPayloadV2Entity = mdmv2.AppleEASNativeMailClientPayloadV2Entity

type AppleEmailPayloadV2Entity = mdmv2.AppleEmailPayloadV2Entity

type AppleEventV2 = mdmv2.AppleEventV2

type AppleGoogleAccountPayloadV2Entity = mdmv2.AppleGoogleAccountPayloadV2Entity

type AppleHomeScreenPayloadV2Entity = mdmv2.AppleHomeScreenPayloadV2Entity

type AppleNotificationPayloadV2Entity = mdmv2.AppleNotificationPayloadV2Entity

type AppleOsXCredentialPayloadEntityV2 = mdmv2.AppleOsXCredentialPayloadEntityV2

type AppleOsXCustomSettingsPayloadEntityV2 = mdmv2.AppleOsXCustomSettingsPayloadEntityV2

type AppleOsXDeviceProfileEntityV2 = mdmv2.AppleOsXDeviceProfileEntityV2

type AppleOsXDiskEncryptionAirWatchPayloadEntityV2 = mdmv2.AppleOsXDiskEncryptionAirWatchPayloadEntityV2

type AppleOsXDiskEncryptionFileVault2PayloadEntityV2 = mdmv2.AppleOsXDiskEncryptionFileVault2PayloadEntityV2

type AppleOsXDiskEncryptionMCXPayloadEntityV2 = mdmv2.AppleOsXDiskEncryptionMCXPayloadEntityV2

type AppleOsXDiskEncryptionPayloadEntityV2 = mdmv2.AppleOsXDiskEncryptionPayloadEntityV2

type AppleOsXEasMicrosoftOutlookPayloadEntityV2 = mdmv2.AppleOsXEasMicrosoftOutlookPayloadEntityV2

type AppleOsXEasNativeMailClientPayloadEntityV2 = mdmv2.AppleOsXEasNativeMailClientPayloadEntityV2

type AppleOsXEmailPayloadEntityV2 = mdmv2.AppleOsXEmailPayloadEntityV2

type AppleOsXMediaAccessEntityV2 = mdmv2.AppleOsXMediaAccessEntityV2

type AppleOsXNetworkAccessAirDropPayloadEntityV2 = mdmv2.AppleOsXNetworkAccessAirDropPayloadEntityV2

type AppleOsXNetworkPayloadEntityV2 = mdmv2.AppleOsXNetworkPayloadEntityV2

type AppleOsXPasscodePayloadEntityV2 = mdmv2.AppleOsXPasscodePayloadEntityV2

type AppleOsXRestrictionAirPrintPayloadEntityV2 = mdmv2.AppleOsXRestrictionAirPrintPayloadEntityV2

type AppleOsXRestrictionAppStorePayloadEntityV2 = mdmv2.AppleOsXRestrictionAppStorePayloadEntityV2

type AppleOsXRestrictionAppleMusicPayloadEntityV2 = mdmv2.AppleOsXRestrictionAppleMusicPayloadEntityV2

type AppleOsXRestrictionApplicationsPayloadEntityV2 = mdmv2.AppleOsXRestrictionApplicationsPayloadEntityV2

type AppleOsXRestrictionBurnsupportPayloadEntityV2 = mdmv2.AppleOsXRestrictionBurnsupportPayloadEntityV2

type AppleOsXRestrictionCameraPayloadEntityV2 = mdmv2.AppleOsXRestrictionCameraPayloadEntityV2

type AppleOsXRestrictionContentCachingPayloadEntityV2 = mdmv2.AppleOsXRestrictionContentCachingPayloadEntityV2

type AppleOsXRestrictionDesktopPayloadEntityV2 = mdmv2.AppleOsXRestrictionDesktopPayloadEntityV2

type AppleOsXRestrictionFunctionalityPayloadEntityV2 = mdmv2.AppleOsXRestrictionFunctionalityPayloadEntityV2

type AppleOsXRestrictionGameCentrePayloadEntityV2 = mdmv2.AppleOsXRestrictionGameCentrePayloadEntityV2

type AppleOsXRestrictionICloudPayloadEntityV2 = mdmv2.AppleOsXRestrictionICloudPayloadEntityV2

type AppleOsXRestrictionMediaPayloadEntityV2 = mdmv2.AppleOsXRestrictionMediaPayloadEntityV2

type AppleOsXRestrictionPasswordsPayloadEntityV2 = mdmv2.AppleOsXRestrictionPasswordsPayloadEntityV2

type AppleOsXRestrictionPreferencesPayloadEntityV2 = mdmv2.AppleOsXRestrictionPreferencesPayloadEntityV2

type AppleOsXRestrictionSafariPayloadEntityV2 = mdmv2.AppleOsXRestrictionSafariPayloadEntityV2

type AppleOsXRestrictionSharingPayloadEntityV2 = mdmv2.AppleOsXRestrictionSharingPayloadEntityV2

type AppleOsXRestrictionSpotlightPayloadEntityV2 = mdmv2.AppleOsXRestrictionSpotlightPayloadEntityV2

type AppleOsXRestrictionWidgetPayloadEntityV2 = mdmv2.AppleOsXRestrictionWidgetPayloadEntityV2

type AppleOsXRestrictionsPayloadEntityV2 = mdmv2.AppleOsXRestrictionsPayloadEntityV2

type AppleOsXScepPayloadEntityV2 = mdmv2.AppleOsXScepPayloadEntityV2

type AppleOsXVpnOnDemandEntityV2 = mdmv2.AppleOsXVpnOnDemandEntityV2

type AppleOsXVpnPayloadEntityV2 = mdmv2.AppleOsXVpnPayloadEntityV2

type ApplePasscodePayloadV2Entity = mdmv2.ApplePasscodePayloadV2Entity

type AppleRestrictionsPayloadV2Entity = mdmv2.AppleRestrictionsPayloadV2Entity

type AppleScepPayloadV2Entity = mdmv2.AppleScepPayloadV2Entity

type AppleSetupAssistantPayloadEntityV2 = mdmv2.AppleSetupAssistantPayloadEntityV2

type AppleSharedDevicePayloadV2Entity = mdmv2.AppleSharedDevicePayloadV2Entity

type AppleSingleSignOnPayloadV2Entity = mdmv2.AppleSingleSignOnPayloadV2Entity

type AppleSsoExtensionPayloadV2Entity = mdmv2.AppleSsoExtensionPayloadV2Entity

type AppleVpnOnDemandEntityV2 = mdmv2.AppleVpnOnDemandEntityV2

type AppleVpnPayloadV2Entity = mdmv2.AppleVpnPayloadV2Entity

type AppleWebClipPayloadV2Entity = mdmv2.AppleWebClipPayloadV2Entity

type AppleWifiPayloadV2Entity = mdmv2.AppleWifiPayloadV2Entity

type ApplicationListEntityV2 = mdmv2.ApplicationListEntityV2

type CertificateMetadataModel1V2 = mdmv2.CertificateMetadataModel1V2

type CertificateMetadataModelV2 = mdmv2.CertificateMetadataModelV2

type CustomDataEntityV2 = mdmv2.CustomDataEntityV2

type CustomDataV2 = mdmv2.CustomDataV2

type DenyRuleV2 = mdmv2.DenyRuleV2

type DeviceProfileV2Entity = mdmv2.DeviceProfileV2Entity

type FirewallRuleV2 = mdmv2.FirewallRuleV2

type GeneralPayloadV2Entity = mdmv2.GeneralPayloadV2Entity

type HomeScreenLayoutFolderV2Entity = mdmv2.HomeScreenLayoutFolderV2Entity

type HomeScreenLayoutPageV2Entity = mdmv2.HomeScreenLayoutPageV2Entity

type HypermediaModelV2 = mdmv2.HypermediaModelV2

type LinkV2 = mdmv2.LinkV2

type MacOsAllowedKernelExtensionsEntityV2 = mdmv2.MacOsAllowedKernelExtensionsEntityV2

type MacOsAllowedSystemExtensionTypesV2Model = mdmv2.MacOsAllowedSystemExtensionTypesV2Model

type MacOsAllowedSystemExtensionV2Model = mdmv2.MacOsAllowedSystemExtensionV2Model

type MacOsAssociatedDomainsPayloadV2Model = mdmv2.MacOsAssociatedDomainsPayloadV2Model

type MacOsCredentialCertificatePreferencePayloadV2Model = mdmv2.MacOsCredentialCertificatePreferencePayloadV2Model

type MacOsCredentialIdentityPreferencePayloadV2Model = mdmv2.MacOsCredentialIdentityPreferencePayloadV2Model

type MacOsCustomAttributePayloadV2Model = mdmv2.MacOsCustomAttributePayloadV2Model

type MacOsGatekeeperPayloadV2Entity = mdmv2.MacOsGatekeeperPayloadV2Entity

type MacOsKernelExtensionPayloadV2Entity = mdmv2.MacOsKernelExtensionPayloadV2Entity

type MacOsPrivacyPreferencesPayloadV2Model = mdmv2.MacOsPrivacyPreferencesPayloadV2Model

type MacOsPrivacyPreferencesV2Model = mdmv2.MacOsPrivacyPreferencesV2Model

type MacOsScepIdentityPreferencePayloadV2Model = mdmv2.MacOsScepIdentityPreferencePayloadV2Model

type MacOsSetupAssistantPayloadEntityV2 = mdmv2.MacOsSetupAssistantPayloadEntityV2

type MacOsSmartCardPayloadV2Model = mdmv2.MacOsSmartCardPayloadV2Model

type MacOsSsoExtensionPayloadV2Entity = mdmv2.MacOsSsoExtensionPayloadV2Entity

type MacOsSystemExtensionsPayloadV2Model = mdmv2.MacOsSystemExtensionsPayloadV2Model

type MacOsWebClipsPayloadV2Entity = mdmv2.MacOsWebClipsPayloadV2Entity

type ProfileDetailsV2Entity = mdmv2.ProfileDetailsV2Entity

type ProfileSearchResultV2Entity = mdmv2.ProfileSearchResultV2Entity

type ProfileSmartGroupV2Entity = mdmv2.ProfileSmartGroupV2Entity

type QnxCustomAttributePayloadEntityV2 = mdmv2.QnxCustomAttributePayloadEntityV2

type QnxDeviceProfileEntityV2 = mdmv2.QnxDeviceProfileEntityV2

type QnxProfileCustomAttributeEntityV2 = mdmv2.QnxProfileCustomAttributeEntityV2

type RedirectRuleV2 = mdmv2.RedirectRuleV2

type RerouteRuleV2 = mdmv2.RerouteRuleV2

type SmartGroupEntityV2 = mdmv2.SmartGroupEntityV2

type SystemUpdateApiMonthDayV2 = mdmv2.SystemUpdateApiMonthDayV2

type WinRTDeviceProfileV2Entity = mdmv2.WinRTDeviceProfileV2Entity

type WinRTIntelCloudPayloadModelV2 = mdmv2.WinRTIntelCloudPayloadModelV2

type WinRTKeepAppsPayloadModelV2 = mdmv2.WinRTKeepAppsPayloadModelV2

type WindowsDesktopAntivirusPayloadEntityV2 = mdmv2.WindowsDesktopAntivirusPayloadEntityV2

type WindowsDesktopApplicationControlPayloadEntityV2 = mdmv2.WindowsDesktopApplicationControlPayloadEntityV2

type WindowsDesktopBiosPayloadEntityV2 = mdmv2.WindowsDesktopBiosPayloadEntityV2

type WindowsDesktopCredentialsPayloadEntityV2 = mdmv2.WindowsDesktopCredentialsPayloadEntityV2

type WindowsDesktopCustomSettingsPayloadEntityV2 = mdmv2.WindowsDesktopCustomSettingsPayloadEntityV2

type WindowsDesktopCustomizationPayloadEntityV2 = mdmv2.WindowsDesktopCustomizationPayloadEntityV2

type WindowsDesktopDefenderExploitGuardPayloadEntityV2 = mdmv2.WindowsDesktopDefenderExploitGuardPayloadEntityV2

type WindowsDesktopDemPayloadModelV2 = mdmv2.WindowsDesktopDemPayloadModelV2

type WindowsDesktopEASPayloadEntityV2 = mdmv2.WindowsDesktopEASPayloadEntityV2

type WindowsDesktopEdpPayloadEntityV2 = mdmv2.WindowsDesktopEdpPayloadEntityV2

type WindowsDesktopEncryptionPayloadEntityV2 = mdmv2.WindowsDesktopEncryptionPayloadEntityV2

type WindowsDesktopExchangeWebServicesPayloadEntityV2 = mdmv2.WindowsDesktopExchangeWebServicesPayloadEntityV2

type WindowsDesktopFirewallPayloadEntityV2 = mdmv2.WindowsDesktopFirewallPayloadEntityV2

type WindowsDesktopFirewallV2PayloadEntity = mdmv2.WindowsDesktopFirewallV2PayloadEntity

type WindowsDesktopKioskPayloadEntityV2 = mdmv2.WindowsDesktopKioskPayloadEntityV2

type WindowsDesktopLicensingPayloadEntityV2 = mdmv2.WindowsDesktopLicensingPayloadEntityV2

type WindowsDesktopOemUpdatePayloadEntityV2 = mdmv2.WindowsDesktopOemUpdatePayloadEntityV2

type WindowsDesktopP2PBranchCachePayloadEntityV2 = mdmv2.WindowsDesktopP2PBranchCachePayloadEntityV2

type WindowsDesktopPasscodePayloadEntityV2 = mdmv2.WindowsDesktopPasscodePayloadEntityV2

type WindowsDesktopPassportPayloadEntityV2 = mdmv2.WindowsDesktopPassportPayloadEntityV2

type WindowsDesktopPersonalizationPayloadEntityV2 = mdmv2.WindowsDesktopPersonalizationPayloadEntityV2

type WindowsDesktopProxyPayloadEntityV2 = mdmv2.WindowsDesktopProxyPayloadEntityV2

type WindowsDesktopRestrictionsPayloadEntityV2 = mdmv2.WindowsDesktopRestrictionsPayloadEntityV2

type WindowsDesktopScepPayloadEntityV2 = mdmv2.WindowsDesktopScepPayloadEntityV2

type WindowsDesktopSingleAppModePayloadEntityV2 = mdmv2.WindowsDesktopSingleAppModePayloadEntityV2

type WindowsDesktopUnifiedWriteFilterPayloadEntityV2 = mdmv2.WindowsDesktopUnifiedWriteFilterPayloadEntityV2

type WindowsDesktopUpdatesPayloadEntityV2 = mdmv2.WindowsDesktopUpdatesPayloadEntityV2

type WindowsDesktopUpdatesV2PayloadEntity = mdmv2.WindowsDesktopUpdatesV2PayloadEntity

type WindowsDesktopVpnPayloadEntityV2 = mdmv2.WindowsDesktopVpnPayloadEntityV2

type WindowsDesktopWebClipsPayloadEntityV2 = mdmv2.WindowsDesktopWebClipsPayloadEntityV2

type WindowsDesktopWifiPayloadEntityV2 = mdmv2.WindowsDesktopWifiPayloadEntityV2

type ProfilesV2SearchProfilesOptions = mdmv2.ProfilesV2SearchProfilesOptions

// --- mdm/v4 (from swagger_patched/mdmv4.json) ---

// ProfilesV4Service service
type ProfilesV4Service = mdmv4.ProfilesV4Service

var NewProfilesV4Service = mdmv4.NewProfilesV4Service

type CertificateMetadataModel1V4 = mdmv4.CertificateMetadataModel1V4

type GeneralPayloadV4Entity = mdmv4.GeneralPayloadV4Entity

type LinuxCredentialsPayloadEntityV4 = mdmv4.LinuxCredentialsPayloadEntityV4

type LinuxCustomConfigurationPayloadEntityV4 = mdmv4.LinuxCustomConfigurationPayloadEntityV4

type LinuxDeviceProfileEntity1V4 = mdmv4.LinuxDeviceProfileEntity1V4

type LinuxWifiPayloadEntityV4 = mdmv4.LinuxWifiPayloadEntityV4

type SmartGroupEntity1V4 = mdmv4.SmartGroupEntity1V4

// --- Layer 2 service wrappers ---

type ProfileService = services.ProfileService
type ProfileResult = services.ProfileResult
type ProfileEntry = services.ProfileEntry

// NewProfileService creates a new ProfileService with eager discovery.
func NewProfileService(ctx context.Context, c *Client) (*ProfileService, error) {
	return services.NewProfileService(ctx, c)
}

// NewProfileServiceWithoutDiscovery creates a ProfileService
// with an empty registry, skipping the eager search call. Pair with
// (ProfileService).RegisterEntry to seed known (id, platform) pairs.
func NewProfileServiceWithoutDiscovery(c *Client) *ProfileService {
	return services.NewProfileServiceWithoutDiscovery(c)
}

// BoolPtr returns a pointer to the given bool value.
func BoolPtr(b bool) *bool { return &b }

// IntPtr returns a pointer to the given int value.
func IntPtr(i int) *int { return &i }

// Int64Ptr returns a pointer to the given int64 value.
func Int64Ptr(i int64) *int64 { return &i }

// Float32Ptr returns a pointer to the given float32 value.
func Float32Ptr(f float32) *float32 { return &f }

// Float64Ptr returns a pointer to the given float64 value.
func Float64Ptr(f float64) *float64 { return &f }

// StringPtr returns a pointer to the given string value.
func StringPtr(s string) *string { return &s }

// Platform constants — exact values returned by the UEM API in General.Platform fields.
const (
	PlatformAndroid       = "Android"
	PlatformAppleiOS      = "Apple iOS"
	PlatformAppleOsX      = "AppleOsX"
	PlatformWindows10     = "Windows 10"
	PlatformWindowsRugged = "Windows_Rugged"
	PlatformLinux         = "To do"
)
