// Code generated by codegen. DO NOT EDIT.

package mdmv2

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/v26/client"
	"net/http"
	"net/url"
)

// DeviceSensorsV2Service provides DeviceSensorsV2 API operations.
type DeviceSensorsV2Service struct {
	client *client.Client
}

// NewDeviceSensorsV2Service creates a new DeviceSensorsV2Service.
func NewDeviceSensorsV2Service(c *client.Client) *DeviceSensorsV2Service {
	return &DeviceSensorsV2Service{client: c}
}

// AddDeviceSensorAssignmentAsync — New - Adds an assignment to device sensor.
// Operation ID: DeviceSensorsV2_AddDeviceSensorAssignmentAsync
// HTTP: POST /api/mdm/devicesensors/{sensorUuid}/assignment
func (s *DeviceSensorsV2Service) AddDeviceSensorAssignmentAsync(
	ctx context.Context,
	SensorUUID string,
	request *DeviceSensorAssignmentRequestV1ModelV2,
) (http.Header, *BaseModelV2, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/devicesensors/%s/assignment", SensorUUID)
	var response BaseModelV2
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("DeviceSensorsV2_AddDeviceSensorAssignmentAsync: %w", err)
	}
	return headers, &response, nil
}

// DeviceSensorsV2BulkUpdateDeviceSensorAssignmentRankingsAsyncOptions holds optional query parameters for BulkUpdateDeviceSensorAssignmentRankingsAsync.
type DeviceSensorsV2BulkUpdateDeviceSensorAssignmentRankingsAsyncOptions struct {
	Action string // Custom action on device sensor assignments. Possible values [update-ranking] update-ranking will update all the rankings provided for device assignments belonging to a specific device sensor.(Required)
}

// BulkUpdateDeviceSensorAssignmentRankingsAsync — New - Bulk update device sensor assignments based on custom action
// Operation ID: DeviceSensorsV2_BulkUpdateDeviceSensorAssignmentRankingsAsync
// HTTP: POST /api/mdm/devicesensors/{sensorUuid}/assignments
func (s *DeviceSensorsV2Service) BulkUpdateDeviceSensorAssignmentRankingsAsync(
	ctx context.Context,
	SensorUUID string,
	request *[]DeviceSensorAssignmentRankingV1ModelV2,
	opts *DeviceSensorsV2BulkUpdateDeviceSensorAssignmentRankingsAsyncOptions,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/devicesensors/%s/assignments", SensorUUID)
	// Validate required query parameters
	if opts == nil {
		return nil, fmt.Errorf("DeviceSensorsV2_BulkUpdateDeviceSensorAssignmentRankingsAsync: opts must not be nil (contains required parameters)")
	}
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		query.Set("action", fmt.Sprintf("%s", opts.Action))
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("DeviceSensorsV2_BulkUpdateDeviceSensorAssignmentRankingsAsync: %w", err)
	}
	return headers, nil
}

// CreateDeviceSensorAsync — New - Create a device sensor.
// Operation ID: DeviceSensorsV2_CreateDeviceSensorAsync
// HTTP: POST /api/mdm/devicesensors
func (s *DeviceSensorsV2Service) CreateDeviceSensorAsync(
	ctx context.Context,
	request *DeviceSensorRequestV2Model,
) (http.Header, *BaseModelV2, error) {
	// Build endpoint path
	endpoint := "/api/mdm/devicesensors"
	var response BaseModelV2
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("DeviceSensorsV2_CreateDeviceSensorAsync: %w", err)
	}
	return headers, &response, nil
}

// DeleteDeviceSensorAssignmentAsync — New - Deletes the device sensor assignment.
// Operation ID: DeviceSensorsV2_DeleteDeviceSensorAssignmentAsync
// HTTP: DELETE /api/mdm/devicesensors/assignments/{assignmentUuid}
func (s *DeviceSensorsV2Service) DeleteDeviceSensorAssignmentAsync(
	ctx context.Context,
	AssignmentUUID string,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/devicesensors/assignments/%s", AssignmentUUID)
	headers, err := s.client.DoRequest(ctx, "DELETE", endpoint, AcceptHeader, "application/json", nil, nil)
	if err != nil {
		return nil, fmt.Errorf("DeviceSensorsV2_DeleteDeviceSensorAssignmentAsync: %w", err)
	}
	return headers, nil
}

// GetDeviceSensorAssignmentAsync — New - Gets the device sensor assignment information.
// Operation ID: DeviceSensorsV2_GetDeviceSensorAssignmentAsync
// HTTP: GET /api/mdm/devicesensors/assignments/{assignmentUuid}
func (s *DeviceSensorsV2Service) GetDeviceSensorAssignmentAsync(
	ctx context.Context,
	AssignmentUUID string,
) (http.Header, *DeviceSensorAssignmentResponseV1ModelV2, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/devicesensors/assignments/%s", AssignmentUUID)
	var response DeviceSensorAssignmentResponseV1ModelV2
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("DeviceSensorsV2_GetDeviceSensorAssignmentAsync: %w", err)
	}
	return headers, &response, nil
}

// GetDeviceSensorAssignmentsAsync — New - Gets the list of device sensor assignments.
// Operation ID: DeviceSensorsV2_GetDeviceSensorAssignmentsAsync
// HTTP: GET /api/mdm/devicesensors/{sensorUuid}/assignments
func (s *DeviceSensorsV2Service) GetDeviceSensorAssignmentsAsync(
	ctx context.Context,
	SensorUUID string,
) (http.Header, *[]DeviceSensorAssignmentResponseV1ModelV2, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/devicesensors/%s/assignments", SensorUUID)
	var response []DeviceSensorAssignmentResponseV1ModelV2
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("DeviceSensorsV2_GetDeviceSensorAssignmentsAsync: %w", err)
	}
	return headers, &response, nil
}

// GetDeviceSensorAsync — New - Gets the device sensor information.
// Operation ID: DeviceSensorsV2_GetDeviceSensorAsync
// HTTP: GET /api/mdm/devicesensors/{sensorUuid}
func (s *DeviceSensorsV2Service) GetDeviceSensorAsync(
	ctx context.Context,
	SensorUUID string,
) (http.Header, *DeviceSensorResponseV2Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/devicesensors/%s", SensorUUID)
	var response DeviceSensorResponseV2Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("DeviceSensorsV2_GetDeviceSensorAsync: %w", err)
	}
	return headers, &response, nil
}

// DeviceSensorsV2GetDeviceSensorsAsyncOptions holds optional query parameters for GetDeviceSensorsAsync.
type DeviceSensorsV2GetDeviceSensorsAsyncOptions struct {
	Name      *string // Filter records based on the sensor name. Partial names are accepted.
	QueryType *string // Filter records based on the query type. Default is None. Accepted values are [POWERSHELL],[BASH] and [PYTHON].
	Platform  *string // Filter records based on the platform. Default is None. Accepted values are [WIN_RT] and [APPLE_OSX].
	Page      *int    // Specific page number to get. 0 based index. Default is 0
	PageSize  *int    // Maximum records per page. Default 500
	OrderBy   *string // Name of the property used for sorting. Default is None. Accepted values are [Name], [Platform] and [QueryType]
	SortOrder *string // Indicates whether the sort order is ascending or descending. The property used for sorting is name. Accepted values are [Asc] and [Desc]. Default value is Asc.
}

// GetDeviceSensorsAsync — New - Gets the list of all the device sensors for the Organization Group.
// Operation ID: DeviceSensorsV2_GetDeviceSensorsAsync
// HTTP: GET /api/mdm/devicesensors/list/{organizationGroupUuid}
func (s *DeviceSensorsV2Service) GetDeviceSensorsAsync(
	ctx context.Context,
	OrganizationGroupUUID string,
	opts *DeviceSensorsV2GetDeviceSensorsAsyncOptions,
) (http.Header, *DeviceSensorListResponseV2Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/devicesensors/list/%s", OrganizationGroupUUID)
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		if opts.Name != nil {
			query.Set("name", fmt.Sprintf("%s", *opts.Name))
		}
		if opts.QueryType != nil {
			query.Set("query_type", fmt.Sprintf("%s", *opts.QueryType))
		}
		if opts.Platform != nil {
			query.Set("platform", fmt.Sprintf("%s", *opts.Platform))
		}
		if opts.Page != nil {
			query.Set("page", fmt.Sprintf("%d", *opts.Page))
		}
		if opts.PageSize != nil {
			query.Set("page_size", fmt.Sprintf("%d", *opts.PageSize))
		}
		if opts.OrderBy != nil {
			query.Set("orderby", fmt.Sprintf("%s", *opts.OrderBy))
		}
		if opts.SortOrder != nil {
			query.Set("sort_order", fmt.Sprintf("%s", *opts.SortOrder))
		}
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response DeviceSensorListResponseV2Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("DeviceSensorsV2_GetDeviceSensorsAsync: %w", err)
	}
	return headers, &response, nil
}

// UpdateDeviceSensorAssignmentAsync — New - Update the device sensor assignment information.
// Operation ID: DeviceSensorsV2_UpdateDeviceSensorAssignmentAsync
// HTTP: PUT /api/mdm/devicesensors/assignments/{assignmentUuid}
func (s *DeviceSensorsV2Service) UpdateDeviceSensorAssignmentAsync(
	ctx context.Context,
	AssignmentUUID string,
	request *DeviceSensorAssignmentRequestV1ModelV2,
) (http.Header, *BaseExceptionModelV2, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/devicesensors/assignments/%s", AssignmentUUID)
	var response BaseExceptionModelV2
	headers, err := s.client.DoRequest(ctx, "PUT", endpoint, AcceptHeader, "application/json", request, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("DeviceSensorsV2_UpdateDeviceSensorAssignmentAsync: %w", err)
	}
	return headers, &response, nil
}

// UpdateDeviceSensorAsync — New - Update the device sensor.
// Operation ID: DeviceSensorsV2_UpdateDeviceSensorAsync
// HTTP: PUT /api/mdm/devicesensors/{sensorUuid}
func (s *DeviceSensorsV2Service) UpdateDeviceSensorAsync(
	ctx context.Context,
	SensorUUID string,
	request *DeviceSensorUpdateV2Model,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/devicesensors/%s", SensorUUID)
	headers, err := s.client.DoRequest(ctx, "PUT", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("DeviceSensorsV2_UpdateDeviceSensorAsync: %w", err)
	}
	return headers, nil
}
