// Code generated by codegen. DO NOT EDIT.

package mamv1

const (
	// AcceptHeader is the Accept header for all services in this package.
	AcceptHeader = "application/json;version=1"
	// ContentType is the default Content-Type for requests in this package.
	ContentType = "application/json"
)
