// Code generated by codegen. DO NOT EDIT.

package mamv1

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/client"
	"net/http"
)

// InternalAppsV1Service provides InternalAppsV1 API operations.
type InternalAppsV1Service struct {
	client *client.Client
}

// NewInternalAppsV1Service creates a new InternalAppsV1Service.
func NewInternalAppsV1Service(c *client.Client) *InternalAppsV1Service {
	return &InternalAppsV1Service{client: c}
}

// AddAssignmentsWithFlexibleDeploymentParametersAsync — Adds assignments along with the flexible deployment parameters to an internal application. Removal date - 29/11/2024.
// Operation ID: InternalAppsV1_AddAssignmentsWithFlexibleDeploymentParametersAsync
// HTTP: POST /api/mam/apps/internal/{applicationId}/assignments
func (s *InternalAppsV1Service) AddAssignmentsWithFlexibleDeploymentParametersAsync(
	ctx context.Context,
	ApplicationID int,
	request *ApplicationAssignmentsModelV1,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mam/apps/internal/%d/assignments", ApplicationID)
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("InternalAppsV1_AddAssignmentsWithFlexibleDeploymentParametersAsync: %w", err)
	}
	return headers, nil
}

// CreateInternalAppFromBlobAsync — Creates an internal application.
// Operation ID: InternalAppsV1_CreateInternalAppFromBlobAsync
// HTTP: POST /api/mam/apps/internal/begininstall
func (s *InternalAppsV1Service) CreateInternalAppFromBlobAsync(
	ctx context.Context,
	request *InternalAppChunkTransactionV1,
) (http.Header, *InternalApplicationEntityV1, error) {
	// Build endpoint path
	endpoint := "/api/mam/apps/internal/begininstall"
	var response InternalApplicationEntityV1
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("InternalAppsV1_CreateInternalAppFromBlobAsync: %w", err)
	}
	return headers, &response, nil
}

// CreateInternalApplicationFromBlob — Creates an internal application.
// Operation ID: InternalAppsV1_CreateInternalApplicationFromBlob
// HTTP: POST /api/mam/apps/internal/application
func (s *InternalAppsV1Service) CreateInternalApplicationFromBlob(
	ctx context.Context,
	request *InternalAppChunkTransactionV1Model,
) (http.Header, *InternalApplicationEntityV1, error) {
	// Build endpoint path
	endpoint := "/api/mam/apps/internal/application"
	var response InternalApplicationEntityV1
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("InternalAppsV1_CreateInternalApplicationFromBlob: %w", err)
	}
	return headers, &response, nil
}

// DeleteInternalAppAsync — Deletes the specified internal application.
// Operation ID: InternalAppsV1_DeleteInternalAppAsync
// HTTP: DELETE /api/mam/apps/internal/{applicationid}
func (s *InternalAppsV1Service) DeleteInternalAppAsync(
	ctx context.Context,
	ApplicationID int,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mam/apps/internal/%d", ApplicationID)
	headers, err := s.client.DoRequest(ctx, "DELETE", endpoint, AcceptHeader, "application/json", nil, nil)
	if err != nil {
		return nil, fmt.Errorf("InternalAppsV1_DeleteInternalAppAsync: %w", err)
	}
	return headers, nil
}

// EditAssignmentsWithFlexibleDeploymentParametersAsync — Edits assignments along with the flexible deployment parameters associated with an internal application.
// Operation ID: InternalAppsV1_EditAssignmentsWithFlexibleDeploymentParametersAsync
// HTTP: PUT /api/mam/apps/internal/{applicationId}/assignments
func (s *InternalAppsV1Service) EditAssignmentsWithFlexibleDeploymentParametersAsync(
	ctx context.Context,
	ApplicationID int,
	request *ApplicationAssignmentsModelV1,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mam/apps/internal/%d/assignments", ApplicationID)
	headers, err := s.client.DoRequest(ctx, "PUT", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("InternalAppsV1_EditAssignmentsWithFlexibleDeploymentParametersAsync: %w", err)
	}
	return headers, nil
}

// GetInternalAppByIdAsync — New - Details of an internal app identified by id.
// Operation ID: InternalAppsV1_GetInternalAppByIdAsync
// HTTP: GET /api/mam/apps/internal/{applicationId}
func (s *InternalAppsV1Service) GetInternalAppByIdAsync(
	ctx context.Context,
	ApplicationID int,
) (http.Header, *InternalAppModelV1, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mam/apps/internal/%d", ApplicationID)
	var response InternalAppModelV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("InternalAppsV1_GetInternalAppByIdAsync: %w", err)
	}
	return headers, &response, nil
}

// InsertInternalApplicationChunkAsync — Uploads the chunk data.
// Operation ID: InternalAppsV1_InsertInternalApplicationChunkAsync
// HTTP: POST /api/mam/apps/internal/uploadchunk
func (s *InternalAppsV1Service) InsertInternalApplicationChunkAsync(
	ctx context.Context,
	request *InternalAppChunkV1,
) (http.Header, *AppChunkTranscationResponseV1, error) {
	// Build endpoint path
	endpoint := "/api/mam/apps/internal/uploadchunk"
	var response AppChunkTranscationResponseV1
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("InternalAppsV1_InsertInternalApplicationChunkAsync: %w", err)
	}
	return headers, &response, nil
}
