// Code generated by codegen. DO NOT EDIT.

package mamv1

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/client"
	"net/http"
)

// MacOsAppsV1Service provides MacOsAppsV1 API operations.
type MacOsAppsV1Service struct {
	client *client.Client
}

// NewMacOsAppsV1Service creates a new MacOsAppsV1Service.
func NewMacOsAppsV1Service(c *client.Client) *MacOsAppsV1Service {
	return &MacOsAppsV1Service{client: c}
}

// CreateMacOSApplication — New - Creates a new macOS application with provided metadata for distribution on macOS Devices
// Operation ID: MacOsAppsV1_CreateMacOSApplication
// HTTP: POST /api/mam/groups/{id}/macos/apps
func (s *MacOsAppsV1Service) CreateMacOSApplication(
	ctx context.Context,
	ID int,
	request *MacOsCreateApplicationRequestV1Model,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mam/groups/%d/macos/apps", ID)
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("MacOsAppsV1_CreateMacOSApplication: %w", err)
	}
	return headers, nil
}
