// Code generated by codegen. DO NOT EDIT.

package mamv1

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/client"
	"net/http"
	"net/url"
)

// PurchasedAppsV1Service provides PurchasedAppsV1 API operations.
type PurchasedAppsV1Service struct {
	client *client.Client
}

// NewPurchasedAppsV1Service creates a new PurchasedAppsV1Service.
func NewPurchasedAppsV1Service(c *client.Client) *PurchasedAppsV1Service {
	return &PurchasedAppsV1Service{client: c}
}

// PurchasedAppsV1VppAppSearchAsyncOptions holds optional query parameters for VppAppSearchAsync.
type PurchasedAppsV1VppAppSearchAsyncOptions struct {
	Applicationname       *string // Application name to search for.
	Isassigned            *bool   // Flag to filter apps by assignment status. true = assigned apps only, false = unassigned apps only.
	Bundleid              *string // Application bundle identifier or package ID to search for.
	Locationgroupid       *int    // Location Group (Organization Group) identifier to search within.
	OrganizationGroupUUID *string // Organization Group UUID to search within.
	Model                 *string // Device model to filter applications by supported models.
	Status                *string // Application status.
	Platform              *string // Device platform to filter applications by supported platforms.
	Page                  *int    // Page number for pagination (0-based index).
	PageSize              *int    // Maximum number of records per page.
	OrderBy               *string // Column name to order results by.
}

// VppAppSearchAsync — New - Search and retrieve details for purchased applications.
// Operation ID: PurchasedAppsV1_VppAppSearchAsync
// HTTP: GET /api/mam/apps/purchased/search
func (s *PurchasedAppsV1Service) VppAppSearchAsync(
	ctx context.Context,
	opts *PurchasedAppsV1VppAppSearchAsyncOptions,
) (http.Header, *PurchasedApplicationSearchResultV1, error) {
	// Build endpoint path
	endpoint := "/api/mam/apps/purchased/search"
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		if opts.Applicationname != nil {
			query.Set("applicationname", fmt.Sprintf("%s", *opts.Applicationname))
		}
		if opts.Isassigned != nil {
			query.Set("isassigned", fmt.Sprintf("%t", *opts.Isassigned))
		}
		if opts.Bundleid != nil {
			query.Set("bundleid", fmt.Sprintf("%s", *opts.Bundleid))
		}
		if opts.Locationgroupid != nil {
			query.Set("locationgroupid", fmt.Sprintf("%d", *opts.Locationgroupid))
		}
		if opts.OrganizationGroupUUID != nil {
			query.Set("organizationgroupuuid", fmt.Sprintf("%s", *opts.OrganizationGroupUUID))
		}
		if opts.Model != nil {
			query.Set("model", fmt.Sprintf("%s", *opts.Model))
		}
		if opts.Status != nil {
			query.Set("status", fmt.Sprintf("%s", *opts.Status))
		}
		if opts.Platform != nil {
			query.Set("platform", fmt.Sprintf("%s", *opts.Platform))
		}
		if opts.Page != nil {
			query.Set("page", fmt.Sprintf("%d", *opts.Page))
		}
		if opts.PageSize != nil {
			query.Set("pagesize", fmt.Sprintf("%d", *opts.PageSize))
		}
		if opts.OrderBy != nil {
			query.Set("orderby", fmt.Sprintf("%s", *opts.OrderBy))
		}
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response PurchasedApplicationSearchResultV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("PurchasedAppsV1_VppAppSearchAsync: %w", err)
	}
	return headers, &response, nil
}
