// Code generated by codegen. DO NOT EDIT.

package mdmv4

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/client"
	"net/http"
)

// ProfilesV4Service provides ProfilesV4 API operations.
type ProfilesV4Service struct {
	client *client.Client
}

// NewProfilesV4Service creates a new ProfilesV4Service.
func NewProfilesV4Service(c *client.Client) *ProfilesV4Service {
	return &ProfilesV4Service{client: c}
}

// CreateLinuxDeviceProfileAsync — Creates a new Linux Device Profile.
// Operation ID: ProfilesV4_CreateLinuxDeviceProfileAsync
// HTTP: POST /api/mdm/profiles/platforms/linux/create
func (s *ProfilesV4Service) CreateLinuxDeviceProfileAsync(
	ctx context.Context,
	request *LinuxDeviceProfileEntity1V4,
) (http.Header, int, error) {
	// Build endpoint path
	endpoint := "/api/mdm/profiles/platforms/linux/create"
	var response int
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, &response)
	if err != nil {
		return nil, 0, fmt.Errorf("ProfilesV4_CreateLinuxDeviceProfileAsync: %w", err)
	}
	return headers, response, nil
}

// UpdateLinuxDeviceProfileAsync — Updates an existing Linux Device Profile.
// Operation ID: ProfilesV4_UpdateLinuxDeviceProfileAsync
// HTTP: POST /api/mdm/profiles/platforms/linux/update
func (s *ProfilesV4Service) UpdateLinuxDeviceProfileAsync(
	ctx context.Context,
	request *LinuxDeviceProfileEntity1V4,
) (http.Header, error) {
	// Build endpoint path
	endpoint := "/api/mdm/profiles/platforms/linux/update"
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("ProfilesV4_UpdateLinuxDeviceProfileAsync: %w", err)
	}
	return headers, nil
}
