// Code generated by codegen. DO NOT EDIT.

package mdmv1

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/v26/client"
	"net/http"
	"net/url"
)

// BaselinesV1Service provides BaselinesV1 API operations.
type BaselinesV1Service struct {
	client *client.Client
}

// NewBaselinesV1Service creates a new BaselinesV1Service.
func NewBaselinesV1Service(c *client.Client) *BaselinesV1Service {
	return &BaselinesV1Service{client: c}
}

// AssignBaselineAsync — Assign smart groups to a baseline (204 empty).
// Operation ID: BaselinesV1_AssignBaselineAsync
// HTTP: POST /api/mdm/groups/{organizationGroupUuid}/baselines/{baselineUuid}/assignments
func (s *BaselinesV1Service) AssignBaselineAsync(
	ctx context.Context,
	OrganizationGroupUUID string,
	BaselineUUID string,
	request *BaselineAssignmentRequestV1Model,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/groups/%s/baselines/%s/assignments", OrganizationGroupUUID, BaselineUUID)
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("BaselinesV1_AssignBaselineAsync: %w", err)
	}
	return headers, nil
}

// BaselinesV1CloneBaselineAsyncOptions holds optional query parameters for CloneBaselineAsync.
type BaselinesV1CloneBaselineAsyncOptions struct {
	Action string // Custom action to apply to the baseline. Only 'clone' is supported.
}

// CloneBaselineAsync — Clone a baseline. Triggered via ?action=clone query parameter (the only supported action).
// Operation ID: BaselinesV1_CloneBaselineAsync
// HTTP: POST /api/mdm/groups/{organizationGroupUuid}/baselines/{baselineUuid}
func (s *BaselinesV1Service) CloneBaselineAsync(
	ctx context.Context,
	OrganizationGroupUUID string,
	BaselineUUID string,
	request *CreateBaselineRequestV1Model,
	opts *BaselinesV1CloneBaselineAsyncOptions,
) (http.Header, *BaselineV1Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/groups/%s/baselines/%s", OrganizationGroupUUID, BaselineUUID)
	// Validate required query parameters
	if opts == nil {
		return nil, nil, fmt.Errorf("BaselinesV1_CloneBaselineAsync: opts must not be nil (contains required parameters)")
	}
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		query.Set("action", fmt.Sprintf("%s", opts.Action))
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response BaselineV1Model
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("BaselinesV1_CloneBaselineAsync: %w", err)
	}
	return headers, &response, nil
}

// DeleteBaselineAsync — Delete a baseline. Canonical impl returns 200 with empty body, not 204.
// Operation ID: BaselinesV1_DeleteBaselineAsync
// HTTP: DELETE /api/mdm/groups/{organizationGroupUuid}/baselines/{baselineUuid}
func (s *BaselinesV1Service) DeleteBaselineAsync(
	ctx context.Context,
	OrganizationGroupUUID string,
	BaselineUUID string,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/groups/%s/baselines/%s", OrganizationGroupUUID, BaselineUUID)
	headers, err := s.client.DoRequest(ctx, "DELETE", endpoint, AcceptHeader, "application/json", nil, nil)
	if err != nil {
		return nil, fmt.Errorf("BaselinesV1_DeleteBaselineAsync: %w", err)
	}
	return headers, nil
}

// GetBaselineAssignmentsAsync — List assignments for a baseline.
// Operation ID: BaselinesV1_GetBaselineAssignmentsAsync
// HTTP: GET /api/mdm/groups/{organizationGroupUuid}/baselines/{baselineUuid}/assignments
func (s *BaselinesV1Service) GetBaselineAssignmentsAsync(
	ctx context.Context,
	OrganizationGroupUUID string,
	BaselineUUID string,
) (http.Header, *[]BaselineAssignmentsV1Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/groups/%s/baselines/%s/assignments", OrganizationGroupUUID, BaselineUUID)
	var response []BaselineAssignmentsV1Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("BaselinesV1_GetBaselineAssignmentsAsync: %w", err)
	}
	return headers, &response, nil
}

// GetBaselineAsync — Get a single baseline.
// Operation ID: BaselinesV1_GetBaselineAsync
// HTTP: GET /api/mdm/groups/{organizationGroupUuid}/baselines/{baselineUuid}
func (s *BaselinesV1Service) GetBaselineAsync(
	ctx context.Context,
	OrganizationGroupUUID string,
	BaselineUUID string,
) (http.Header, *BaselineV1Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/groups/%s/baselines/%s", OrganizationGroupUUID, BaselineUUID)
	var response BaselineV1Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("BaselinesV1_GetBaselineAsync: %w", err)
	}
	return headers, &response, nil
}

// BaselinesV1GetBaselineDevicePoliciesAsyncOptions holds optional query parameters for GetBaselineDevicePoliciesAsync.
type BaselinesV1GetBaselineDevicePoliciesAsyncOptions struct {
	Offset          *int    // Number of policies to skip (default 0).
	Limit           *int    // Maximum number of policies to return (default 10).
	ComplianceLevel *string // Comma-separated compliance statuses to include: NotAvailable, NonCompliant, Intermediate, Compliant. Default: no filter.
	SortBy          *string // Sort column (default Name).
	SortOrder       *string // asc (default), or desc/descending.
	Language        *string // Language code for policy text (default en-US).
}

// GetBaselineDevicePoliciesAsync — Get per-policy compliance details for one device under a baseline.
// Operation ID: BaselinesV1_GetBaselineDevicePoliciesAsync
// HTTP: GET /api/mdm/groups/{organizationGroupUuid}/baselines/{baselineUuid}/devices/{deviceUuid}/policies
func (s *BaselinesV1Service) GetBaselineDevicePoliciesAsync(
	ctx context.Context,
	OrganizationGroupUUID string,
	BaselineUUID string,
	DeviceUUID string,
	opts *BaselinesV1GetBaselineDevicePoliciesAsyncOptions,
) (http.Header, *BaselineDevicePoliciesV1Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/groups/%s/baselines/%s/devices/%s/policies", OrganizationGroupUUID, BaselineUUID, DeviceUUID)
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		if opts.Offset != nil {
			query.Set("offset", fmt.Sprintf("%d", *opts.Offset))
		}
		if opts.Limit != nil {
			query.Set("limit", fmt.Sprintf("%d", *opts.Limit))
		}
		if opts.ComplianceLevel != nil {
			query.Set("compliance_level", fmt.Sprintf("%s", *opts.ComplianceLevel))
		}
		if opts.SortBy != nil {
			query.Set("sort_by", fmt.Sprintf("%s", *opts.SortBy))
		}
		if opts.SortOrder != nil {
			query.Set("sort_order", fmt.Sprintf("%s", *opts.SortOrder))
		}
		if opts.Language != nil {
			query.Set("language", fmt.Sprintf("%s", *opts.Language))
		}
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response BaselineDevicePoliciesV1Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("BaselinesV1_GetBaselineDevicePoliciesAsync: %w", err)
	}
	return headers, &response, nil
}

// GetBaselineDevicesAsync — List devices that have the baseline assigned (paged Page/PageSize/Total/Results wrapper).
// Operation ID: BaselinesV1_GetBaselineDevicesAsync
// HTTP: GET /api/mdm/groups/{organizationGroupUuid}/baselines/{baselineUuid}/devices
func (s *BaselinesV1Service) GetBaselineDevicesAsync(
	ctx context.Context,
	OrganizationGroupUUID string,
	BaselineUUID string,
) (http.Header, *GetBaselineDeviceSummaryResponseV1Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/groups/%s/baselines/%s/devices", OrganizationGroupUUID, BaselineUUID)
	var response GetBaselineDeviceSummaryResponseV1Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("BaselinesV1_GetBaselineDevicesAsync: %w", err)
	}
	return headers, &response, nil
}

// GetBaselineStatusAsync — Get compliance status for a baseline.
// Operation ID: BaselinesV1_GetBaselineStatusAsync
// HTTP: GET /api/mdm/groups/{organizationGroupUuid}/baselines/{baselineUuid}/status
func (s *BaselinesV1Service) GetBaselineStatusAsync(
	ctx context.Context,
	OrganizationGroupUUID string,
	BaselineUUID string,
) (http.Header, *[]BaselineStatusV1Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/groups/%s/baselines/%s/status", OrganizationGroupUUID, BaselineUUID)
	var response []BaselineStatusV1Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("BaselinesV1_GetBaselineStatusAsync: %w", err)
	}
	return headers, &response, nil
}

// GetBaselinesAsync — List baselines for an organization group.
// Operation ID: BaselinesV1_GetBaselinesAsync
// HTTP: GET /api/mdm/groups/{organizationGroupUuid}/baselines
func (s *BaselinesV1Service) GetBaselinesAsync(
	ctx context.Context,
	OrganizationGroupUUID string,
) (http.Header, *[]BaselineV1Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/groups/%s/baselines", OrganizationGroupUUID)
	var response []BaselineV1Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("BaselinesV1_GetBaselinesAsync: %w", err)
	}
	return headers, &response, nil
}

// UpdateBaselineAsync — Update a baseline. Canonical impl returns 200 + body, not 204.
// Operation ID: BaselinesV1_UpdateBaselineAsync
// HTTP: PUT /api/mdm/groups/{organizationGroupUuid}/baselines/{baselineUuid}
func (s *BaselinesV1Service) UpdateBaselineAsync(
	ctx context.Context,
	OrganizationGroupUUID string,
	BaselineUUID string,
	request *UpdateBaselineRequestV1Model,
) (http.Header, *BaselineV1Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/groups/%s/baselines/%s", OrganizationGroupUUID, BaselineUUID)
	var response BaselineV1Model
	headers, err := s.client.DoRequest(ctx, "PUT", endpoint, AcceptHeader, "application/json", request, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("BaselinesV1_UpdateBaselineAsync: %w", err)
	}
	return headers, &response, nil
}
