// Code generated by codegen. DO NOT EDIT.

package mdmv1

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/v26/client"
	"net/http"
	"net/url"
)

// CatalogsV1Service provides CatalogsV1 API operations.
type CatalogsV1Service struct {
	client *client.Client
}

// NewCatalogsV1Service creates a new CatalogsV1Service.
func NewCatalogsV1Service(c *client.Client) *CatalogsV1Service {
	return &CatalogsV1Service{client: c}
}

// CatalogsV1GetAllPoliciesAsyncOptions holds optional query parameters for GetAllPoliciesAsync.
type CatalogsV1GetAllPoliciesAsyncOptions struct {
	Q        *string // The search text
	Language *string // The language code (Default en-US)
	Offset   *string // The number of records to skip (Default 0).
	Limit    *string // The maximum number of rows to return (Default 10)
}

// GetAllPoliciesAsync — New - Search policies in the Policy catalog of a specific version
// Operation ID: CatalogsV1_GetAllPoliciesAsync
// HTTP: GET /api/mdm/baselines/catalogs/{osVersionUUID}/policies
func (s *CatalogsV1Service) GetAllPoliciesAsync(
	ctx context.Context,
	OsVersionUUID string,
	opts *CatalogsV1GetAllPoliciesAsyncOptions,
) (http.Header, *GetAllPoliciesResponseV1Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/baselines/catalogs/%s/policies", OsVersionUUID)
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		if opts.Q != nil {
			query.Set("q", fmt.Sprintf("%s", *opts.Q))
		}
		if opts.Language != nil {
			query.Set("language", fmt.Sprintf("%s", *opts.Language))
		}
		if opts.Offset != nil {
			query.Set("offset", fmt.Sprintf("%s", *opts.Offset))
		}
		if opts.Limit != nil {
			query.Set("limit", fmt.Sprintf("%s", *opts.Limit))
		}
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response GetAllPoliciesResponseV1Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("CatalogsV1_GetAllPoliciesAsync: %w", err)
	}
	return headers, &response, nil
}

// CatalogsV1GetPolicyAsyncOptions holds optional query parameters for GetPolicyAsync.
type CatalogsV1GetPolicyAsyncOptions struct {
	Language *string // The language code (Default en-US)
}

// GetPolicyAsync — New - Fetch a policy with it's options
// Operation ID: CatalogsV1_GetPolicyAsync
// HTTP: GET /api/mdm/baselines/catalogs/policies/{policyUUID}
func (s *CatalogsV1Service) GetPolicyAsync(
	ctx context.Context,
	PolicyUUID string,
	opts *CatalogsV1GetPolicyAsyncOptions,
) (http.Header, *PolicyModelV1, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/baselines/catalogs/policies/%s", PolicyUUID)
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		if opts.Language != nil {
			query.Set("language", fmt.Sprintf("%s", *opts.Language))
		}
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response PolicyModelV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("CatalogsV1_GetPolicyAsync: %w", err)
	}
	return headers, &response, nil
}

// CatalogsV1GetPolicyCatalogAsyncOptions holds optional query parameters for GetPolicyCatalogAsync.
type CatalogsV1GetPolicyCatalogAsyncOptions struct {
	Language *string // The language code (Default en-US)
}

// GetPolicyCatalogAsync — New - Fetch policy catalog for the given operating system version.
// Operation ID: CatalogsV1_GetPolicyCatalogAsync
// HTTP: GET /api/mdm/baselines/catalogs/{osVersionUUID}
func (s *CatalogsV1Service) GetPolicyCatalogAsync(
	ctx context.Context,
	OsVersionUUID string,
	opts *CatalogsV1GetPolicyCatalogAsyncOptions,
) (http.Header, *PolicyCatalogModelV1, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/baselines/catalogs/%s", OsVersionUUID)
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		if opts.Language != nil {
			query.Set("language", fmt.Sprintf("%s", *opts.Language))
		}
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response PolicyCatalogModelV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("CatalogsV1_GetPolicyCatalogAsync: %w", err)
	}
	return headers, &response, nil
}
