// Code generated by codegen. DO NOT EDIT.

package mdmv1

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/v26/client"
	"net/http"
	"net/url"
)

// DeviceSensorsService provides DeviceSensors API operations.
type DeviceSensorsService struct {
	client *client.Client
}

// NewDeviceSensorsService creates a new DeviceSensorsService.
func NewDeviceSensorsService(c *client.Client) *DeviceSensorsService {
	return &DeviceSensorsService{client: c}
}

// DeviceSensorsGetDeviceSensorsByDeviceUuidAsyncOptions holds optional query parameters for GetDeviceSensorsByDeviceUuidAsync.
type DeviceSensorsGetDeviceSensorsByDeviceUuidAsyncOptions struct {
	SearchText *string // Filter records based on the sensor name and value. Pattern search will be performed.
	Limit      *int    // An integer that indicates the maximum number of results to return. Valid input range for this property is 1 to 2000. (Default value - 50).
	Offset     *int    // An integer describing the starting position in the result set. Valid input range for this property is 0 to 2000. (Default value - 0).
	OrderBy    *string // Name of the property used for sorting. Default is Name. Accepted values are [name] and [last_executed_at].
	SortOrder  *string // Whether the sort order is ascending or descending. Default value is Asc. Accepted values are [Asc] and [Desc].
}

// GetDeviceSensorsByDeviceUuidAsync — New - Returns the list of sensors reported by the specified device.
// Operation ID: DeviceSensors_GetDeviceSensorsByDeviceUuidAsync
// HTTP: GET /api/mdm/devices/{deviceUuid}/sensors
func (s *DeviceSensorsService) GetDeviceSensorsByDeviceUuidAsync(
	ctx context.Context,
	DeviceUUID string,
	opts *DeviceSensorsGetDeviceSensorsByDeviceUuidAsyncOptions,
) (http.Header, *DeviceSensorSearchResponseModelV1, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/devices/%s/sensors", DeviceUUID)
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		if opts.SearchText != nil {
			query.Set("search_text", fmt.Sprintf("%s", *opts.SearchText))
		}
		if opts.Limit != nil {
			query.Set("limit", fmt.Sprintf("%d", *opts.Limit))
		}
		if opts.Offset != nil {
			query.Set("offset", fmt.Sprintf("%d", *opts.Offset))
		}
		if opts.OrderBy != nil {
			query.Set("orderby", fmt.Sprintf("%s", *opts.OrderBy))
		}
		if opts.SortOrder != nil {
			query.Set("sort_order", fmt.Sprintf("%s", *opts.SortOrder))
		}
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response DeviceSensorSearchResponseModelV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("DeviceSensors_GetDeviceSensorsByDeviceUuidAsync: %w", err)
	}
	return headers, &response, nil
}
