// Code generated by codegen. DO NOT EDIT.

package mdmv1

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/client"
	"net/http"
)

// OSVersionsV1Service provides OSVersionsV1 API operations.
type OSVersionsV1Service struct {
	client *client.Client
}

// NewOSVersionsV1Service creates a new OSVersionsV1Service.
func NewOSVersionsV1Service(c *client.Client) *OSVersionsV1Service {
	return &OSVersionsV1Service{client: c}
}

// GetActiveOSVersionsAsync — New - Retrieves a list of active os versions
// Operation ID: OSVersionsV1_GetActiveOSVersionsAsync
// HTTP: GET /api/mdm/baselines/osversions
func (s *OSVersionsV1Service) GetActiveOSVersionsAsync(
	ctx context.Context,
) (http.Header, *[]OSVersionV1Model, error) {
	// Build endpoint path
	endpoint := "/api/mdm/baselines/osversions"
	var response []OSVersionV1Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("OSVersionsV1_GetActiveOSVersionsAsync: %w", err)
	}
	return headers, &response, nil
}

// GetActiveOSVersionsForPlatformAsync — New - Retrieves a list of active os versions for a platform
// Operation ID: OSVersionsV1_GetActiveOSVersionsForPlatformAsync
// HTTP: GET /api/mdm/baselines/osversions/{platformUUID}
func (s *OSVersionsV1Service) GetActiveOSVersionsForPlatformAsync(
	ctx context.Context,
	PlatformUUID string,
) (http.Header, *[]OSVersionV2ModelV1, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/baselines/osversions/%s", PlatformUUID)
	var response []OSVersionV2ModelV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("OSVersionsV1_GetActiveOSVersionsForPlatformAsync: %w", err)
	}
	return headers, &response, nil
}
