// Code generated by codegen. DO NOT EDIT.

package mdmv1

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/client"
	"net/http"
)

// PlatformsV1Service provides PlatformsV1 API operations.
type PlatformsV1Service struct {
	client *client.Client
}

// NewPlatformsV1Service creates a new PlatformsV1Service.
func NewPlatformsV1Service(c *client.Client) *PlatformsV1Service {
	return &PlatformsV1Service{client: c}
}

// GetActivePlatformsAsync — New - Retrieves a list of active platforms.
// Operation ID: PlatformsV1_GetActivePlatformsAsync
// HTTP: GET /api/mdm/baselines/platforms
func (s *PlatformsV1Service) GetActivePlatformsAsync(
	ctx context.Context,
) (http.Header, *[]PlatformV2ModelV1, error) {
	// Build endpoint path
	endpoint := "/api/mdm/baselines/platforms"
	var response []PlatformV2ModelV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("PlatformsV1_GetActivePlatformsAsync: %w", err)
	}
	return headers, &response, nil
}
