// Code generated by codegen. DO NOT EDIT.

package mdmv1

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/client"
	"net/http"
)

// ScriptAssignmentV1Service provides ScriptAssignmentV1 API operations.
type ScriptAssignmentV1Service struct {
	client *client.Client
}

// NewScriptAssignmentV1Service creates a new ScriptAssignmentV1Service.
func NewScriptAssignmentV1Service(c *client.Client) *ScriptAssignmentV1Service {
	return &ScriptAssignmentV1Service{client: c}
}

// AddScriptAssignmentAsync — New - AddScriptAssignmentAsync
// Operation ID: ScriptAssignmentV1_AddScriptAssignmentAsync
// HTTP: POST /api/mdm/scripts/{scriptUuid}/assignments
func (s *ScriptAssignmentV1Service) AddScriptAssignmentAsync(
	ctx context.Context,
	ScriptUUID string,
	request *CreateScriptAssignmentV1,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/scripts/%s/assignments", ScriptUUID)
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("ScriptAssignmentV1_AddScriptAssignmentAsync: %w", err)
	}
	return headers, nil
}

// BulkUpdateScriptAssignmentsAsync — New - BulkUpdateScriptAssignmentsAsync
// Operation ID: ScriptAssignmentV1_BulkUpdateScriptAssignmentsAsync
// HTTP: POST /api/mdm/scripts/{scriptUuid}/updateassignments
func (s *ScriptAssignmentV1Service) BulkUpdateScriptAssignmentsAsync(
	ctx context.Context,
	ScriptUUID string,
	request *BulkUpdateScriptAssignmentV1,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/scripts/%s/updateassignments", ScriptUUID)
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("ScriptAssignmentV1_BulkUpdateScriptAssignmentsAsync: %w", err)
	}
	return headers, nil
}

// GetScriptAssignmentAsync — New - GetScriptAssignmentAsync
// Operation ID: ScriptAssignmentV1_GetScriptAssignmentAsync
// HTTP: GET /api/mdm/scriptassignments/{assignmentUuid}
func (s *ScriptAssignmentV1Service) GetScriptAssignmentAsync(
	ctx context.Context,
	AssignmentUUID string,
) (http.Header, *ScriptAssignmentResourceV1, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/scriptassignments/%s", AssignmentUUID)
	var response ScriptAssignmentResourceV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("ScriptAssignmentV1_GetScriptAssignmentAsync: %w", err)
	}
	return headers, &response, nil
}

// GetScriptAssignmentsAsync — New - GetScriptAssignmentsAsync
// Operation ID: ScriptAssignmentV1_GetScriptAssignmentsAsync
// HTTP: GET /api/mdm/scripts/{scriptUuid}/assignments
func (s *ScriptAssignmentV1Service) GetScriptAssignmentsAsync(
	ctx context.Context,
	ScriptUUID string,
) (http.Header, *ScriptAssignmentsSearchResultV1, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/scripts/%s/assignments", ScriptUUID)
	var response ScriptAssignmentsSearchResultV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("ScriptAssignmentV1_GetScriptAssignmentsAsync: %w", err)
	}
	return headers, &response, nil
}
