// Code generated by codegen. DO NOT EDIT.

package mdmv1

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/client"
	"net/http"
	"net/url"
)

// ScriptsV1Service provides ScriptsV1 API operations.
type ScriptsV1Service struct {
	client *client.Client
}

// NewScriptsV1Service creates a new ScriptsV1Service.
func NewScriptsV1Service(c *client.Client) *ScriptsV1Service {
	return &ScriptsV1Service{client: c}
}

// CreateScriptAsync — New - CreateScriptAsync
// Operation ID: ScriptsV1_CreateScriptAsync
// HTTP: POST /api/mdm/groups/{organizationGroupUuid}/scripts
func (s *ScriptsV1Service) CreateScriptAsync(
	ctx context.Context,
	OrganizationGroupUUID string,
	request *CreateScriptV1,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/groups/%s/scripts", OrganizationGroupUUID)
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("ScriptsV1_CreateScriptAsync: %w", err)
	}
	return headers, nil
}

// GetScriptAsync — New - GetScriptAsync
// Operation ID: ScriptsV1_GetScriptAsync
// HTTP: GET /api/mdm/scripts/{scriptUuid}
func (s *ScriptsV1Service) GetScriptAsync(
	ctx context.Context,
	ScriptUUID string,
) (http.Header, *ScriptResourceV1, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/scripts/%s", ScriptUUID)
	var response ScriptResourceV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("ScriptsV1_GetScriptAsync: %w", err)
	}
	return headers, &response, nil
}

// GetScriptSamplesAsync — New - Get script samples.
// Operation ID: ScriptsV1_GetScriptSamplesAsync
// HTTP: POST /api/mdm/groups/{organizationGroupUuid}/scripts/samples
func (s *ScriptsV1Service) GetScriptSamplesAsync(
	ctx context.Context,
	OrganizationGroupUUID string,
	request *ScriptSampleSearchRequestModelV1,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/groups/%s/scripts/samples", OrganizationGroupUUID)
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("ScriptsV1_GetScriptSamplesAsync: %w", err)
	}
	return headers, nil
}

// ScriptsV1GetScriptsByOrganizationGroupAsyncOptions holds optional query parameters for GetScriptsByOrganizationGroupAsync.
type ScriptsV1GetScriptsByOrganizationGroupAsyncOptions struct {
	Expand     bool    // Flag to specify to get metadata or complete definition of a script
	Name       *string // Filter records based on the script name. Partial names are accepted.
	ScriptType *string // Filter records based on the script type. Accepted values are [POWERSHELL] when platform is [WIN_RT], [BASH] and [PYTHON] when platform is [APPLE_OSX].
	Platform   *string // Filter records based on the platform. Default is None. Accepted values are [WIN_RT] and [APPLE_OSX].
	Category   *string // Filter records based on the script category.Default is None. Accept values like [IT-UTILITIES] and etc.
	Page       *int    // Specific page number to get. 0 based index. Default is 0
	PageSize   *int    // Maximum records per page. Default 500
	OrderBy    *string // Name of the property used for sorting. Accepted values are [Name], [Platform], [ScriptType], [Category] and [ActionType]
	SortOrder  *string // Whether the sort order is ascending or descending for specified orderby. The default property used for sorting is name. Accepted values are [Asc] and [Desc]. Default value is Asc.
}

// GetScriptsByOrganizationGroupAsync — New - GetScriptsByOrganizationGroupAsync
// Operation ID: ScriptsV1_GetScriptsByOrganizationGroupAsync
// HTTP: GET /api/mdm/groups/{organizationGroupUuid}/scripts
func (s *ScriptsV1Service) GetScriptsByOrganizationGroupAsync(
	ctx context.Context,
	OrganizationGroupUUID string,
	opts *ScriptsV1GetScriptsByOrganizationGroupAsyncOptions,
) (http.Header, *ScriptsSearchResultV1, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/groups/%s/scripts", OrganizationGroupUUID)
	// Validate required query parameters
	if opts == nil {
		return nil, nil, fmt.Errorf("ScriptsV1_GetScriptsByOrganizationGroupAsync: opts must not be nil (contains required parameters)")
	}
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		query.Set("expand", fmt.Sprintf("%t", opts.Expand))
		if opts.Name != nil {
			query.Set("name", fmt.Sprintf("%s", *opts.Name))
		}
		if opts.ScriptType != nil {
			query.Set("script_type", fmt.Sprintf("%s", *opts.ScriptType))
		}
		if opts.Platform != nil {
			query.Set("platform", fmt.Sprintf("%s", *opts.Platform))
		}
		if opts.Category != nil {
			query.Set("category", fmt.Sprintf("%s", *opts.Category))
		}
		if opts.Page != nil {
			query.Set("page", fmt.Sprintf("%d", *opts.Page))
		}
		if opts.PageSize != nil {
			query.Set("page_size", fmt.Sprintf("%d", *opts.PageSize))
		}
		if opts.OrderBy != nil {
			query.Set("orderby", fmt.Sprintf("%s", *opts.OrderBy))
		}
		if opts.SortOrder != nil {
			query.Set("sort_order", fmt.Sprintf("%s", *opts.SortOrder))
		}
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response ScriptsSearchResultV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("ScriptsV1_GetScriptsByOrganizationGroupAsync: %w", err)
	}
	return headers, &response, nil
}

// ReplaceScriptDefinitionAsync — New - ReplaceScriptDefinitionAsync
// Operation ID: ScriptsV1_ReplaceScriptDefinitionAsync
// HTTP: PUT /api/mdm/scripts/{scriptUuid}
func (s *ScriptsV1Service) ReplaceScriptDefinitionAsync(
	ctx context.Context,
	ScriptUUID string,
	request *UpdateScriptV1,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/scripts/%s", ScriptUUID)
	headers, err := s.client.DoRequest(ctx, "PUT", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("ScriptsV1_ReplaceScriptDefinitionAsync: %w", err)
	}
	return headers, nil
}

// ScriptBulkDeleteAsync — New - ScriptBulkDelete
// Operation ID: ScriptsV1_ScriptBulkDeleteAsync
// HTTP: POST /api/mdm/groups/{organizationGroupUuid}/scripts/bulkdelete
func (s *ScriptsV1Service) ScriptBulkDeleteAsync(
	ctx context.Context,
	OrganizationGroupUUID string,
	request *[]string,
) (http.Header, *DeleteScriptResourceV1, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/groups/%s/scripts/bulkdelete", OrganizationGroupUUID)
	var response DeleteScriptResourceV1
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("ScriptsV1_ScriptBulkDeleteAsync: %w", err)
	}
	return headers, &response, nil
}
