// Code generated by codegen. DO NOT EDIT.

package mdmv1

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/client"
	"net/http"
	"net/url"
)

// SmartGroupsService provides SmartGroups API operations.
type SmartGroupsService struct {
	client *client.Client
}

// NewSmartGroupsService creates a new SmartGroupsService.
func NewSmartGroupsService(c *client.Client) *SmartGroupsService {
	return &SmartGroupsService{client: c}
}

// CreateSmartGroupAsync — Creates a smart group in Airwatch.
// Operation ID: SmartGroups_CreateSmartGroupAsync
// HTTP: POST /api/mdm/smartgroups
func (s *SmartGroupsService) CreateSmartGroupAsync(
	ctx context.Context,
	request *SmartGroupEditV1Model,
) (http.Header, *SmartGroupCreateResponseV1, error) {
	// Build endpoint path
	endpoint := "/api/mdm/smartgroups"
	var response SmartGroupCreateResponseV1
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("SmartGroups_CreateSmartGroupAsync: %w", err)
	}
	return headers, &response, nil
}

// DeleteAsync — Deletes the Smart Group identified by the Smart Group Identifier.
// Operation ID: SmartGroups_DeleteAsync
// HTTP: DELETE /api/mdm/smartgroups/{id}
func (s *SmartGroupsService) DeleteAsync(
	ctx context.Context,
	ID int,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/smartgroups/%d", ID)
	headers, err := s.client.DoRequest(ctx, "DELETE", endpoint, AcceptHeader, "application/json", nil, nil)
	if err != nil {
		return nil, fmt.Errorf("SmartGroups_DeleteAsync: %w", err)
	}
	return headers, nil
}

// LoadSmartGroupAsync — Retrieves the Smart Group Details.
// Operation ID: SmartGroups_LoadSmartGroupAsync
// HTTP: GET /api/mdm/smartgroups/{id}
func (s *SmartGroupsService) LoadSmartGroupAsync(
	ctx context.Context,
	ID int,
) (http.Header, *SmartGroupV1, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/smartgroups/%d", ID)
	var response SmartGroupV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("SmartGroups_LoadSmartGroupAsync: %w", err)
	}
	return headers, &response, nil
}

// SmartGroupsSearchAsyncOptions holds optional query parameters for SearchAsync.
type SmartGroupsSearchAsyncOptions struct {
	Name                         *string         // SmartGroup name.
	OrganizationGroupID          *int            // Organization Group identifier.
	ManagedByOrganizationGroupID *int            // Smart group managing organization group identifier.
	ModifiedFrom                 *client.UEMTime // DateTime, Filters the result where SmartGroup modified date is greater or equal to modifiedfrom value.
	ModifiedTill                 *client.UEMTime // DateTime, Filters the result where SmartGroup modified date is less or equal to modifiedtill value.
	OrderBy                      *string         // Order by column name.
	SortOrder                    *string         // Sorting order. Values ASC or DESC. Defaults to ASC.
	Page                         *int            // Page number.
	PageSize                     *int            // Records per page.
}

// SearchAsync — Searches for smart groups using the query information provided.
// Operation ID: SmartGroups_SearchAsync
// HTTP: GET /api/mdm/smartgroups/search
func (s *SmartGroupsService) SearchAsync(
	ctx context.Context,
	opts *SmartGroupsSearchAsyncOptions,
) (http.Header, *SmartGroupSearchResultV1, error) {
	// Build endpoint path
	endpoint := "/api/mdm/smartgroups/search"
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		if opts.Name != nil {
			query.Set("name", fmt.Sprintf("%s", *opts.Name))
		}
		if opts.OrganizationGroupID != nil {
			query.Set("organizationgroupid", fmt.Sprintf("%d", *opts.OrganizationGroupID))
		}
		if opts.ManagedByOrganizationGroupID != nil {
			query.Set("managedbyorganizationgroupid", fmt.Sprintf("%d", *opts.ManagedByOrganizationGroupID))
		}
		if opts.ModifiedFrom != nil {
			query.Set("modifiedfrom", fmt.Sprintf("%v", *opts.ModifiedFrom))
		}
		if opts.ModifiedTill != nil {
			query.Set("modifiedtill", fmt.Sprintf("%v", *opts.ModifiedTill))
		}
		if opts.OrderBy != nil {
			query.Set("orderby", fmt.Sprintf("%s", *opts.OrderBy))
		}
		if opts.SortOrder != nil {
			query.Set("sortorder", fmt.Sprintf("%s", *opts.SortOrder))
		}
		if opts.Page != nil {
			query.Set("page", fmt.Sprintf("%d", *opts.Page))
		}
		if opts.PageSize != nil {
			query.Set("pagesize", fmt.Sprintf("%d", *opts.PageSize))
		}
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response SmartGroupSearchResultV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("SmartGroups_SearchAsync: %w", err)
	}
	return headers, &response, nil
}

// UpdateSmartGroupAsync — Updates the details of the specified Smart Group.
// Operation ID: SmartGroups_UpdateSmartGroupAsync
// HTTP: PUT /api/mdm/smartgroups/{id}
func (s *SmartGroupsService) UpdateSmartGroupAsync(
	ctx context.Context,
	ID int,
	request *SmartGroupEditV1Model,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/smartgroups/%d", ID)
	headers, err := s.client.DoRequest(ctx, "PUT", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("SmartGroups_UpdateSmartGroupAsync: %w", err)
	}
	return headers, nil
}
