// Code generated by codegen. DO NOT EDIT.

package mdmv1

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/client"
	"net/http"
	"net/url"
)

// SmartGroupsService provides SmartGroups API operations.
type SmartGroupsService struct {
	client *client.Client
}

// NewSmartGroupsService creates a new SmartGroupsService.
func NewSmartGroupsService(c *client.Client) *SmartGroupsService {
	return &SmartGroupsService{client: c}
}

// SmartGroupsSearchOptions holds optional query parameters for Search.
type SmartGroupsSearchOptions struct {
	Name                         *string         // SmartGroup name.
	OrganizationGroupID          *int            // Organization Group identifier.
	ManagedByOrganizationGroupID *int            // Smart group managing organization group identifier.
	ModifiedFrom                 *client.UEMTime // DateTime, Filters the result where SmartGroup modified date is greater or equal to modifiedfrom value.
	ModifiedTill                 *client.UEMTime // DateTime, Filters the result where SmartGroup modified date is less or equal to modifiedtill value.
	OrderBy                      *string         // Order by column name.
	SortOrder                    *string         // Sorting order. Values ASC or DESC. Defaults to ASC.
	Page                         *int            // Page number.
	PageSize                     *int            // Records per page.
}

// Search — Searches for smart groups using the query information provided.
// Operation ID: SmartGroups_Search
// HTTP: GET /api/mdm/smartgroups/search
func (s *SmartGroupsService) Search(
	ctx context.Context,
	opts *SmartGroupsSearchOptions,
) (http.Header, *SmartGroupSearchResultV1, error) {
	// Build endpoint path
	endpoint := "/api/mdm/smartgroups/search"
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		if opts.Name != nil {
			query.Set("name", fmt.Sprintf("%s", *opts.Name))
		}
		if opts.OrganizationGroupID != nil {
			query.Set("organizationgroupid", fmt.Sprintf("%d", *opts.OrganizationGroupID))
		}
		if opts.ManagedByOrganizationGroupID != nil {
			query.Set("managedbyorganizationgroupid", fmt.Sprintf("%d", *opts.ManagedByOrganizationGroupID))
		}
		if opts.ModifiedFrom != nil {
			query.Set("modifiedfrom", fmt.Sprintf("%v", *opts.ModifiedFrom))
		}
		if opts.ModifiedTill != nil {
			query.Set("modifiedtill", fmt.Sprintf("%v", *opts.ModifiedTill))
		}
		if opts.OrderBy != nil {
			query.Set("orderby", fmt.Sprintf("%s", *opts.OrderBy))
		}
		if opts.SortOrder != nil {
			query.Set("sortorder", fmt.Sprintf("%s", *opts.SortOrder))
		}
		if opts.Page != nil {
			query.Set("page", fmt.Sprintf("%d", *opts.Page))
		}
		if opts.PageSize != nil {
			query.Set("pagesize", fmt.Sprintf("%d", *opts.PageSize))
		}
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response SmartGroupSearchResultV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("SmartGroups_Search: %w", err)
	}
	return headers, &response, nil
}
