// Code generated by codegen. DO NOT EDIT.

package mdmv1

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/v26/client"
	"net/http"
	"net/url"
)

// TemplatesV1Service provides TemplatesV1 API operations.
type TemplatesV1Service struct {
	client *client.Client
}

// NewTemplatesV1Service creates a new TemplatesV1Service.
func NewTemplatesV1Service(c *client.Client) *TemplatesV1Service {
	return &TemplatesV1Service{client: c}
}

// GetAllAsync — New - Fetch GPO templates
// Operation ID: TemplatesV1_GetAllAsync
// HTTP: GET /api/mdm/baselines/templates
func (s *TemplatesV1Service) GetAllAsync(
	ctx context.Context,
) (http.Header, *[]BaselineVendorTemplateV1Model, error) {
	// Build endpoint path
	endpoint := "/api/mdm/baselines/templates"
	var response []BaselineVendorTemplateV1Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("TemplatesV1_GetAllAsync: %w", err)
	}
	return headers, &response, nil
}

// TemplatesV1GetPolicyAsyncOptions holds optional query parameters for GetPolicyAsync.
type TemplatesV1GetPolicyAsyncOptions struct {
	Language *string // The language code (Default en-US)
}

// GetPolicyAsync — New - Fetch a policy with it's recommended values
// Operation ID: TemplatesV1_GetPolicyAsync
// HTTP: GET /api/mdm/baselines/templates/{baselineTemplateUUID}/policies/{policyUUID}
func (s *TemplatesV1Service) GetPolicyAsync(
	ctx context.Context,
	BaselineTemplateUUID string,
	PolicyUUID string,
	opts *TemplatesV1GetPolicyAsyncOptions,
) (http.Header, *PolicyModelV1, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/baselines/templates/%s/policies/%s", BaselineTemplateUUID, PolicyUUID)
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		if opts.Language != nil {
			query.Set("language", fmt.Sprintf("%s", *opts.Language))
		}
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response PolicyModelV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("TemplatesV1_GetPolicyAsync: %w", err)
	}
	return headers, &response, nil
}

// TemplatesV1SearchTemplateAsyncOptions holds optional query parameters for SearchTemplateAsync.
type TemplatesV1SearchTemplateAsyncOptions struct {
	OsVersionUUID     string  // The operating system version identifier(Required)
	SecurityLevelUUID *string // The security level identifier
	PolicyTree        *bool   // load the policy tree
	Language          *string // The language code (Default en-US)
}

// SearchTemplateAsync — New - Find a vendor template
// Operation ID: TemplatesV1_SearchTemplateAsync
// HTTP: GET /api/mdm/baselines/templates/search/{vendorTemplateUUID}
func (s *TemplatesV1Service) SearchTemplateAsync(
	ctx context.Context,
	VendorTemplateUUID string,
	opts *TemplatesV1SearchTemplateAsyncOptions,
) (http.Header, *BaselineTemplateV1, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/baselines/templates/search/%s", VendorTemplateUUID)
	// Validate required query parameters
	if opts == nil {
		return nil, nil, fmt.Errorf("TemplatesV1_SearchTemplateAsync: opts must not be nil (contains required parameters)")
	}
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		query.Set("osVersionUUID", fmt.Sprintf("%s", opts.OsVersionUUID))
		if opts.SecurityLevelUUID != nil {
			query.Set("securityLevelUUID", fmt.Sprintf("%s", *opts.SecurityLevelUUID))
		}
		if opts.PolicyTree != nil {
			query.Set("policyTree", fmt.Sprintf("%t", *opts.PolicyTree))
		}
		if opts.Language != nil {
			query.Set("language", fmt.Sprintf("%s", *opts.Language))
		}
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response BaselineTemplateV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("TemplatesV1_SearchTemplateAsync: %w", err)
	}
	return headers, &response, nil
}
