// Code generated by codegen. DO NOT EDIT.

package mdmv1

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/client"
	"net/http"
	"net/url"
)

// UpdatesV1Service provides UpdatesV1 API operations.
type UpdatesV1Service struct {
	client *client.Client
}

// NewUpdatesV1Service creates a new UpdatesV1Service.
func NewUpdatesV1Service(c *client.Client) *UpdatesV1Service {
	return &UpdatesV1Service{client: c}
}

// UpdatesV1BulkUpdateDeviceUpdateDeploymentOptions holds optional query parameters for BulkUpdateDeviceUpdateDeployment.
type UpdatesV1BulkUpdateDeviceUpdateDeploymentOptions struct {
	Action string // Custom action on deployments. Possible values [update-ranking] update-ranking will update all the rankings provided for device update deployments belonging to a specific device update and Organization Group.
}

// BulkUpdateDeviceUpdateDeployment — New - Bulk update device update deployments based on custom action.
// Operation ID: UpdatesV1_BulkUpdateDeviceUpdateDeployment
// HTTP: POST /api/mdm/updates/{updateUuid}/groups/{organizationGroupUuid}/deployments
func (s *UpdatesV1Service) BulkUpdateDeviceUpdateDeployment(
	ctx context.Context,
	UpdateUUID string,
	OrganizationGroupUUID string,
	request *[]DeviceUpdateDeploymentRankingV1Model,
	opts *UpdatesV1BulkUpdateDeviceUpdateDeploymentOptions,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/updates/%s/groups/%s/deployments", UpdateUUID, OrganizationGroupUUID)
	// Validate required query parameters
	if opts == nil {
		return nil, fmt.Errorf("UpdatesV1_BulkUpdateDeviceUpdateDeployment: opts must not be nil (contains required parameters)")
	}
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		query.Set("action", fmt.Sprintf("%s", opts.Action))
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("UpdatesV1_BulkUpdateDeviceUpdateDeployment: %w", err)
	}
	return headers, nil
}

// CreateUpdateDeployment — New - Creates a deployment for a specific device update.
// Operation ID: UpdatesV1_CreateUpdateDeployment
// HTTP: POST /api/mdm/updates/{updateUuid}/groups/{organizationGroupUuid}/deployment
func (s *UpdatesV1Service) CreateUpdateDeployment(
	ctx context.Context,
	UpdateUUID string,
	OrganizationGroupUUID string,
	request *DeviceUpdateDeploymentBaseV1Model,
) (http.Header, *BaseModelV1, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/updates/%s/groups/%s/deployment", UpdateUUID, OrganizationGroupUUID)
	var response BaseModelV1
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", request, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("UpdatesV1_CreateUpdateDeployment: %w", err)
	}
	return headers, &response, nil
}

// DeleteDeviceUpdateDeployment — New - Deletes the device update deployment.
// Operation ID: UpdatesV1_DeleteDeviceUpdateDeployment
// HTTP: DELETE /api/mdm/updates/deployments/{uuid}
func (s *UpdatesV1Service) DeleteDeviceUpdateDeployment(
	ctx context.Context,
	UUID string,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/updates/deployments/%s", UUID)
	headers, err := s.client.DoRequest(ctx, "DELETE", endpoint, AcceptHeader, "application/json", nil, nil)
	if err != nil {
		return nil, fmt.Errorf("UpdatesV1_DeleteDeviceUpdateDeployment: %w", err)
	}
	return headers, nil
}

// UpdatesV1DevicesUpdateActionOptions holds optional query parameters for DevicesUpdateAction.
type UpdatesV1DevicesUpdateActionOptions struct {
	Action string // Action for device update. [START, STOP] are accepted values.
}

// DevicesUpdateAction — New - Starts or stops the roll out of the device update for the specific Organization Group.
// Operation ID: UpdatesV1_DevicesUpdateAction
// HTTP: POST /api/mdm/updates/{updateUuid}/groups/{organizationGroupUuid}
func (s *UpdatesV1Service) DevicesUpdateAction(
	ctx context.Context,
	UpdateUUID string,
	OrganizationGroupUUID string,
	opts *UpdatesV1DevicesUpdateActionOptions,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/updates/%s/groups/%s", UpdateUUID, OrganizationGroupUUID)
	// Validate required query parameters
	if opts == nil {
		return nil, fmt.Errorf("UpdatesV1_DevicesUpdateAction: opts must not be nil (contains required parameters)")
	}
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		query.Set("action", fmt.Sprintf("%s", opts.Action))
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	headers, err := s.client.DoRequest(ctx, "POST", endpoint, AcceptHeader, "application/json", nil, nil)
	if err != nil {
		return nil, fmt.Errorf("UpdatesV1_DevicesUpdateAction: %w", err)
	}
	return headers, nil
}

// GetCountOfDeviceStatus — New - Gets the breakdown of device statuses for a given device update at the specified Organization Group
// Operation ID: UpdatesV1_GetCountOfDeviceStatus
// HTTP: GET /api/mdm/updates/{updateUuid}/groups/{organizationGroupUuid}/device-status
func (s *UpdatesV1Service) GetCountOfDeviceStatus(
	ctx context.Context,
	UpdateUUID string,
	OrganizationGroupUUID string,
) (http.Header, *DeviceUpdateCountDeviceStatusV1Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/updates/%s/groups/%s/device-status", UpdateUUID, OrganizationGroupUUID)
	var response DeviceUpdateCountDeviceStatusV1Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("UpdatesV1_GetCountOfDeviceStatus: %w", err)
	}
	return headers, &response, nil
}

// UpdatesV1GetDeploymentsByDeviceUpdateOptions holds optional query parameters for GetDeploymentsByDeviceUpdate.
type UpdatesV1GetDeploymentsByDeviceUpdateOptions struct {
	OrganizationGroupUUID string // Organization Group UUID.
}

// GetDeploymentsByDeviceUpdate — New - Get deployments for a device update at a specific Organization Group.
// Operation ID: UpdatesV1_GetDeploymentsByDeviceUpdate
// HTTP: GET /api/mdm/updates/{uuid}/deployments
func (s *UpdatesV1Service) GetDeploymentsByDeviceUpdate(
	ctx context.Context,
	UUID string,
	opts *UpdatesV1GetDeploymentsByDeviceUpdateOptions,
) (http.Header, *[]DeploymentV1Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/updates/%s/deployments", UUID)
	// Validate required query parameters
	if opts == nil {
		return nil, nil, fmt.Errorf("UpdatesV1_GetDeploymentsByDeviceUpdate: opts must not be nil (contains required parameters)")
	}
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		query.Set("organization_group_uuid", fmt.Sprintf("%s", opts.OrganizationGroupUUID))
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response []DeploymentV1Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("UpdatesV1_GetDeploymentsByDeviceUpdate: %w", err)
	}
	return headers, &response, nil
}

// GetDeviceReadiness — New - Gets device readiness for a given device update at the specified Organization Group.
// Operation ID: UpdatesV1_GetDeviceReadiness
// HTTP: GET /api/mdm/updates/{updateUuid}/groups/{organizationGroupUuid}/device-readiness
func (s *UpdatesV1Service) GetDeviceReadiness(
	ctx context.Context,
	UpdateUUID string,
	OrganizationGroupUUID string,
) (http.Header, *DeviceUpdateDeviceReadinessV1Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/updates/%s/groups/%s/device-readiness", UpdateUUID, OrganizationGroupUUID)
	var response DeviceUpdateDeviceReadinessV1Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("UpdatesV1_GetDeviceReadiness: %w", err)
	}
	return headers, &response, nil
}

// GetDeviceUpdateDeploymentDetails — New - Gets the device update deployment details.
// Operation ID: UpdatesV1_GetDeviceUpdateDeploymentDetails
// HTTP: GET /api/mdm/updates/deployments/{uuid}
func (s *UpdatesV1Service) GetDeviceUpdateDeploymentDetails(
	ctx context.Context,
	UUID string,
) (http.Header, *DeviceUpdateDeploymentV1Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/updates/deployments/%s", UUID)
	var response DeviceUpdateDeploymentV1Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("UpdatesV1_GetDeviceUpdateDeploymentDetails: %w", err)
	}
	return headers, &response, nil
}

// UpdatesV1GetDeviceUpdateStatusBySearchParametersOptions holds optional query parameters for GetDeviceUpdateStatusBySearchParameters.
type UpdatesV1GetDeviceUpdateStatusBySearchParametersOptions struct {
	DeviceName *string // Filter records based on the device name.
	User       *string // Filter records based on the device user. Accepted values are user's first name or last name.
	Status     *string // Filter records based on update status. Accepted values are DOWNLOADING, DOWNLOAD_FAILED, INSTALLING, INSTALL_FAILED, DOWNLOAD_COMPLETE, INSTALL_COMPLETE, NOT_STARTED, IDLE
	Reason     *string // Filter records based on the reason for update status. Accepted values are IDLE, DOWNLOADING, DOWNLOAD_FAILED, DOWNLOAD_REQUIRES_COMPUTER, DOWNLOAD_INSUFFICIENT_SPACE, DOWNLOAD_INSUFFICIENT_POWER, DOWNLOAD_INSUFFICIENT_NETWORK, INSTALLING, INSTALL_INSUFFICIENT_SPACE, INSTALL_INSUFFICIENT_POWER, INSTALL_PHONE_CALL_INPROGRESS, INSTALL_FAILED, DOWNLOAD_COMPLETE, INSTALL_COMPLETE, NOT_STARTED
	Page       *int    // Page number which will be fetched. 1 based index. Default 1.
	PageSize   *int    // Maximum number of results to be returned in one page. Default 50.
}

// GetDeviceUpdateStatusBySearchParameters — New - Gets the device update status for all the assigned devices by search parameters
// Operation ID: UpdatesV1_GetDeviceUpdateStatusBySearchParameters
// HTTP: GET /api/mdm/updates/{updateUuid}/groups/{organizationGroupUuid}/update-status
func (s *UpdatesV1Service) GetDeviceUpdateStatusBySearchParameters(
	ctx context.Context,
	UpdateUUID string,
	OrganizationGroupUUID string,
	opts *UpdatesV1GetDeviceUpdateStatusBySearchParametersOptions,
) (http.Header, *DeviceUpdateStatusPagedSearchResultsV1Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/updates/%s/groups/%s/update-status", UpdateUUID, OrganizationGroupUUID)
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		if opts.DeviceName != nil {
			query.Set("device_name", fmt.Sprintf("%s", *opts.DeviceName))
		}
		if opts.User != nil {
			query.Set("user", fmt.Sprintf("%s", *opts.User))
		}
		if opts.Status != nil {
			query.Set("status", fmt.Sprintf("%s", *opts.Status))
		}
		if opts.Reason != nil {
			query.Set("reason", fmt.Sprintf("%s", *opts.Reason))
		}
		if opts.Page != nil {
			query.Set("page", fmt.Sprintf("%d", *opts.Page))
		}
		if opts.PageSize != nil {
			query.Set("page_size", fmt.Sprintf("%d", *opts.PageSize))
		}
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response DeviceUpdateStatusPagedSearchResultsV1Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("UpdatesV1_GetDeviceUpdateStatusBySearchParameters: %w", err)
	}
	return headers, &response, nil
}

// UpdatesV1GetDeviceUpdatesBySearchParametersOptions holds optional query parameters for GetDeviceUpdatesBySearchParameters.
type UpdatesV1GetDeviceUpdatesBySearchParametersOptions struct {
	OrganizationGroupUUID  string          // Organization Group UUID.
	Platform               *string         // Platform name Ex. Apple, AppleOSX, AppleTV.
	Page                   *int            // Page number which will be fetched. 1 based index. Default 1.
	PageSize               *int            // Maximum number of results to be returned in one page. Default 50.
	UpdateName             *string         // Filter records based on the update name.
	Version                *string         // Filter records based on the update version.
	ReleaseDate            *string         // Filter records based on the update release date. Accepted values are LastSevenDays, LastThirtyDays, LastThreeMonths, LastSixMonths, Custom
	ExpirationDate         *string         // Filter records based on the update expiration date. Accepted values are NextSevenDays, NextThirtyDays, NextThreeMonths, NextSixMonths, Custom
	CustomReleaseStartDate *client.UEMTime // Filter records starting from custom release start date. Example formats are "yyyy/MM/dd", "yyyy-MM-dd", "MM/dd/yyyy", "MM-dd-yyyy"
	CustomReleaseEndDate   *client.UEMTime // Filter records starting from custom release end date. Example formats are "yyyy/MM/dd", "yyyy-MM-dd", "MM/dd/yyyy", "MM-dd-yyyy"
	CustomExpiryStartDate  *client.UEMTime // Filter records starting from custom expiry start date. Example formats are "yyyy/MM/dd", "yyyy-MM-dd", "MM/dd/yyyy", "MM-dd-yyyy"
	CustomExpiryEndDate    *client.UEMTime // Filter records starting from custom expiry end date. Example formats are "yyyy/MM/dd", "yyyy-MM-dd", "MM/dd/yyyy", "MM-dd-yyyy"
	UpdateAvailable        *bool           // Filter records based on the update status.
}

// GetDeviceUpdatesBySearchParameters — New - Get device updates by search parameters
// Operation ID: UpdatesV1_GetDeviceUpdatesBySearchParameters
// HTTP: GET /api/mdm/updates
func (s *UpdatesV1Service) GetDeviceUpdatesBySearchParameters(
	ctx context.Context,
	opts *UpdatesV1GetDeviceUpdatesBySearchParametersOptions,
) (http.Header, *DeviceUpdatePagedSearchResultsV1Model, error) {
	// Build endpoint path
	endpoint := "/api/mdm/updates"
	// Validate required query parameters
	if opts == nil {
		return nil, nil, fmt.Errorf("UpdatesV1_GetDeviceUpdatesBySearchParameters: opts must not be nil (contains required parameters)")
	}
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		query.Set("organization_group_uuid", fmt.Sprintf("%s", opts.OrganizationGroupUUID))
		if opts.Platform != nil {
			query.Set("platform", fmt.Sprintf("%s", *opts.Platform))
		}
		if opts.Page != nil {
			query.Set("page", fmt.Sprintf("%d", *opts.Page))
		}
		if opts.PageSize != nil {
			query.Set("page_size", fmt.Sprintf("%d", *opts.PageSize))
		}
		if opts.UpdateName != nil {
			query.Set("update_name", fmt.Sprintf("%s", *opts.UpdateName))
		}
		if opts.Version != nil {
			query.Set("version", fmt.Sprintf("%s", *opts.Version))
		}
		if opts.ReleaseDate != nil {
			query.Set("release_date", fmt.Sprintf("%s", *opts.ReleaseDate))
		}
		if opts.ExpirationDate != nil {
			query.Set("expiration_date", fmt.Sprintf("%s", *opts.ExpirationDate))
		}
		if opts.CustomReleaseStartDate != nil {
			query.Set("custom_release_start_date", fmt.Sprintf("%v", *opts.CustomReleaseStartDate))
		}
		if opts.CustomReleaseEndDate != nil {
			query.Set("custom_release_end_date", fmt.Sprintf("%v", *opts.CustomReleaseEndDate))
		}
		if opts.CustomExpiryStartDate != nil {
			query.Set("custom_expiry_start_date", fmt.Sprintf("%v", *opts.CustomExpiryStartDate))
		}
		if opts.CustomExpiryEndDate != nil {
			query.Set("custom_expiry_end_date", fmt.Sprintf("%v", *opts.CustomExpiryEndDate))
		}
		if opts.UpdateAvailable != nil {
			query.Set("update_available", fmt.Sprintf("%t", *opts.UpdateAvailable))
		}
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response DeviceUpdatePagedSearchResultsV1Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("UpdatesV1_GetDeviceUpdatesBySearchParameters: %w", err)
	}
	return headers, &response, nil
}

// GetSpecificUpdateDetails — New - Get Specific device update details.
// Operation ID: UpdatesV1_GetSpecificUpdateDetails
// HTTP: GET /api/mdm/updates/{uuid}
func (s *UpdatesV1Service) GetSpecificUpdateDetails(
	ctx context.Context,
	UUID string,
) (http.Header, *DeviceUpdateDetailsSupportedDevicesV1Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/updates/%s", UUID)
	var response DeviceUpdateDetailsSupportedDevicesV1Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("UpdatesV1_GetSpecificUpdateDetails: %w", err)
	}
	return headers, &response, nil
}

// UpdateDeviceUpdateDeployment — New - Updates the device update deployment.
// Operation ID: UpdatesV1_UpdateDeviceUpdateDeployment
// HTTP: PUT /api/mdm/updates/deployments/{uuid}
func (s *UpdatesV1Service) UpdateDeviceUpdateDeployment(
	ctx context.Context,
	UUID string,
	request *DeviceUpdateDeploymentUpdateV1Model,
) (http.Header, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/mdm/updates/deployments/%s", UUID)
	headers, err := s.client.DoRequest(ctx, "PUT", endpoint, AcceptHeader, "application/json", request, nil)
	if err != nil {
		return nil, fmt.Errorf("UpdatesV1_UpdateDeviceUpdateDeployment: %w", err)
	}
	return headers, nil
}
