// Code generated by codegen. DO NOT EDIT.

package systemv1

// EntityIdV1 is a generated model type.

type EntityIdV1 struct {
	Value *int64 `json:"Value,omitempty"`
}

// EntityReferenceV1 is a generated model type.

type EntityReferenceV1 struct {
	ID   *EntityIdV1 `json:"Id,omitempty"`
	Name string      `json:"Name,omitempty"`
	UUID string      `json:"Uuid,omitempty"`
}

// LocationGroupSearchResultV1 represents The LocationGroupSearchResult class.

type LocationGroupSearchResultV1 struct {
	// Gets or sets location group list.
	LocationGroups []LocationGroupV1 `json:"LocationGroups,omitempty"`
	Page           *int              `json:"Page,omitempty"`
	PageSize       *int              `json:"PageSize,omitempty"`
	Total          *int              `json:"Total,omitempty"`
}

// LocationGroupV1 represents This entity represents a location group.

type LocationGroupV1 struct {
	// Gets or sets this tells whether default location to be created while creating Location Group.
	AddDefaultLocation string `json:"AddDefaultLocation,omitempty"`
	// Gets or sets this contains total number of Admin users in this Location Group.
	Admins string `json:"Admins,omitempty"`
	// Gets or sets country name like United States, India etc.
	Country string `json:"Country,omitempty"`
	// Gets or sets date and time when Location group was created.
	CreatedOn string `json:"CreatedOn,omitempty"`
	// Gets or sets this contains total nummber of devices in this Location group.
	Devices string `json:"Devices,omitempty"`
	// Gets or sets the location group's tenant code.
	GroupID string      `json:"GroupId,omitempty"`
	ID      *EntityIdV1 `json:"Id,omitempty"`
	// Gets or sets a value indicating whether customer type OG is present in parent OG hierarchy.
	IsCustomerTypeExistInParentHierarchy *bool `json:"IsCustomerTypeExistInParentHierarchy,omitempty"`
	// Gets or sets location Group Hierarchy level, like 0[Operating Location group], 1[immediate children],2 etc... This value is valid when retrieving children for location group.
	LgLevel *int `json:"LgLevel,omitempty"`
	// Gets or sets locale information for Location Group like.
	Locale string `json:"Locale,omitempty"`
	// Gets or sets location group type like Business segment, Customer etc...
	LocationGroupType string `json:"LocationGroupType,omitempty"`
	// Gets or sets the location group name.
	Name                string             `json:"Name,omitempty"`
	ParentLocationGroup *EntityReferenceV1 `json:"ParentLocationGroup,omitempty"`
	// Gets or sets this contains total number of Enrollment users in this Location Group.
	Users string `json:"Users,omitempty"`
	UUID  string `json:"Uuid,omitempty"`
}

// OrganizationGroupCollectionV1Model represents Model class that holds collection organization groups.

type OrganizationGroupCollectionV1Model struct {
	// Collection of organization group uuids
	Items []string `json:"items,omitempty"`
}
