// Code generated by codegen. DO NOT EDIT.

package systemv1

import (
	"context"
	"fmt"
	"github.com/euc-oss/terraform-sdk-uem/v26/client"
	"net/http"
	"net/url"
)

// OrganizationGroupsService provides OrganizationGroups API operations.
type OrganizationGroupsService struct {
	client *client.Client
}

// NewOrganizationGroupsService creates a new OrganizationGroupsService.
func NewOrganizationGroupsService(c *client.Client) *OrganizationGroupsService {
	return &OrganizationGroupsService{client: c}
}

// GetAsync — Retrieves information about the specified organization group.
// Operation ID: OrganizationGroups_GetAsync
// HTTP: GET /api/system/groups/{id}
func (s *OrganizationGroupsService) GetAsync(
	ctx context.Context,
	ID int,
) (http.Header, *LocationGroupV1, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/system/groups/%d", ID)
	var response LocationGroupV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("OrganizationGroups_GetAsync: %w", err)
	}
	return headers, &response, nil
}

// GetChildLocationGroups — Provides a list of child organization groups of the specified organization group.
// Operation ID: OrganizationGroups_GetChildLocationGroups
// HTTP: GET /api/system/groups/{id}/children
func (s *OrganizationGroupsService) GetChildLocationGroups(
	ctx context.Context,
	ID int,
) (http.Header, *[]LocationGroupV1, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/system/groups/%d/children", ID)
	var response []LocationGroupV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("OrganizationGroups_GetChildLocationGroups: %w", err)
	}
	return headers, &response, nil
}

// GetParents — Get the ancestor organization groups of the given org group, up to the Global OG
// Operation ID: OrganizationGroups_GetParents
// HTTP: GET /api/system/groups/{uuid}/parents
func (s *OrganizationGroupsService) GetParents(
	ctx context.Context,
	UUID string,
) (http.Header, *OrganizationGroupCollectionV1Model, error) {
	// Build endpoint path
	endpoint := fmt.Sprintf("/api/system/groups/%s/parents", UUID)
	var response OrganizationGroupCollectionV1Model
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("OrganizationGroups_GetParents: %w", err)
	}
	return headers, &response, nil
}

// OrganizationGroupsLocationGroupSearchOptions holds optional query parameters for LocationGroupSearch.
type OrganizationGroupsLocationGroupSearchOptions struct {
	Name      *string // The OrganizationGroup name, such as "Global".
	Type      *string // The OrganizationGroup type. (eg. "Container","Customer","Partner").
	Groupid   *string // The organization group identifier[Activation code] to search for.[Exact match is performed for this attribute].
	OrderBy   *string // Orders the results based on this attribute-value[Valid values are: Id/Name/GroupId/LocationGroupType].
	Page      *int    // Specific page number to get. 0 based index.
	PageSize  *int    // Maximum records per page. Default 500.
	SortOrder *string // Sorting order. Allowed values are ASC or DESC. Defaults to ASC if this attribute is not specified.
}

// LocationGroupSearch — Searches for organization groups using the query information provided.
// Operation ID: OrganizationGroups_LocationGroupSearch
// HTTP: GET /api/system/groups/search
func (s *OrganizationGroupsService) LocationGroupSearch(
	ctx context.Context,
	opts *OrganizationGroupsLocationGroupSearchOptions,
) (http.Header, *LocationGroupSearchResultV1, error) {
	// Build endpoint path
	endpoint := "/api/system/groups/search"
	// Build query parameters
	if opts != nil {
		query := url.Values{}
		if opts.Name != nil {
			query.Set("name", fmt.Sprintf("%s", *opts.Name))
		}
		if opts.Type != nil {
			query.Set("type", fmt.Sprintf("%s", *opts.Type))
		}
		if opts.Groupid != nil {
			query.Set("groupid", fmt.Sprintf("%s", *opts.Groupid))
		}
		if opts.OrderBy != nil {
			query.Set("orderby", fmt.Sprintf("%s", *opts.OrderBy))
		}
		if opts.Page != nil {
			query.Set("page", fmt.Sprintf("%d", *opts.Page))
		}
		if opts.PageSize != nil {
			query.Set("pagesize", fmt.Sprintf("%d", *opts.PageSize))
		}
		if opts.SortOrder != nil {
			query.Set("sortorder", fmt.Sprintf("%s", *opts.SortOrder))
		}
		if len(query) > 0 {
			endpoint = endpoint + "?" + query.Encode()
		}
	}
	var response LocationGroupSearchResultV1
	headers, err := s.client.DoRequest(ctx, "GET", endpoint, AcceptHeader, "application/json", nil, &response)
	if err != nil {
		return nil, nil, fmt.Errorf("OrganizationGroups_LocationGroupSearch: %w", err)
	}
	return headers, &response, nil
}
